/********************************************************************************
** Form generated from reading UI file 'ventanaconfigurar.ui'
**
** Created by: Qt User Interface Compiler version 6.1.3
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_VENTANACONFIGURAR_H
#define UI_VENTANACONFIGURAR_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_VentanaConfigurar
{
public:
    QWidget *centralwidget;
    QGroupBox *insertarPaquete;
    QLineEdit *lineEdit;
    QLabel *label;
    QLabel *label_2;
    QLineEdit *lineEdit_2;
    QLabel *label_3;
    QLineEdit *lineEdit_3;
    QPushButton *pushButton;
    QGroupBox *groupBox;
    QLabel *label_4;
    QLineEdit *lineEdit_4;
    QLabel *label_5;
    QLineEdit *lineEdit_5;
    QPushButton *pushButton_2;
    QGroupBox *groupBox_2;
    QLabel *label_6;
    QLineEdit *lineEdit_6;
    QLabel *label_7;
    QLineEdit *lineEdit_7;
    QPushButton *pushButton_3;
    QLabel *label_8;
    QLineEdit *lineEdit_8;
    QGroupBox *groupBox_3;
    QLabel *label_9;
    QLineEdit *lineEdit_9;
    QLabel *label_10;
    QPushButton *pushButton_4;
    QLabel *label_11;
    QLineEdit *lineEdit_11;
    QLineEdit *lineEdit_12;
    QLineEdit *lineEdit_13;
    QLabel *label_12;
    QGroupBox *groupBox_4;
    QLabel *label_13;
    QLineEdit *lineEdit_10;
    QLabel *label_14;
    QPushButton *pushButton_5;
    QLabel *label_15;
    QLineEdit *lineEdit_14;
    QLineEdit *lineEdit_15;
    QLineEdit *lineEdit_16;
    QLabel *label_16;
    QGroupBox *groupBox_5;
    QLabel *label_17;
    QLineEdit *lineEdit_17;
    QLabel *label_18;
    QPushButton *pushButton_6;
    QLabel *label_19;
    QLineEdit *lineEdit_18;
    QLineEdit *lineEdit_19;
    QLineEdit *lineEdit_20;
    QLabel *label_20;
    QGroupBox *groupBox_6;
    QLabel *label_21;
    QLineEdit *lineEdit_21;
    QPushButton *pushButton_7;
    QGroupBox *groupBox_7;
    QLabel *label_22;
    QLineEdit *lineEdit_22;
    QPushButton *pushButton_8;
    QGroupBox *groupBox_8;
    QLabel *label_24;
    QLineEdit *lineEdit_24;
    QLabel *label_25;
    QPushButton *pushButton_10;
    QLineEdit *lineEdit_26;
    QGroupBox *groupBox_9;
    QLabel *label_26;
    QLineEdit *lineEdit_25;
    QPushButton *pushButton_11;
    QGroupBox *groupBox_10;
    QLabel *label_27;
    QLineEdit *lineEdit_27;
    QPushButton *pushButton_12;
    QGroupBox *groupBox_11;
    QLineEdit *lineEdit_28;
    QRadioButton *radioButton;
    QPushButton *pushButton_13;
    QGroupBox *groupBox_12;
    QLineEdit *lineEdit_29;
    QRadioButton *radioButton_2;
    QPushButton *pushButton_14;
    QGroupBox *groupBox_13;
    QLineEdit *lineEdit_30;
    QRadioButton *radioButton_3;
    QPushButton *pushButton_15;
    QRadioButton *radioButton_4;
    QGroupBox *groupBox_14;
    QLineEdit *lineEdit_31;
    QRadioButton *radioButton_5;
    QPushButton *pushButton_16;
    QRadioButton *radioButton_6;
    QGroupBox *groupBox_15;
    QLineEdit *lineEdit_33;
    QRadioButton *radioButton_9;
    QPushButton *pushButton_18;
    QRadioButton *radioButton_10;
    QGroupBox *groupBox_16;
    QLineEdit *lineEdit_34;
    QRadioButton *radioButton_11;
    QPushButton *pushButton_19;
    QRadioButton *radioButton_12;
    QGroupBox *groupBox_17;
    QLabel *label_28;
    QLineEdit *lineEdit_35;
    QPushButton *pushButton_20;
    QGroupBox *groupBox_18;
    QLabel *label_29;
    QLineEdit *lineEdit_36;
    QPushButton *pushButton_21;
    QLineEdit *lineEdit_37;
    QLabel *label_30;
    QGroupBox *groupBox_22;
    QLabel *label_37;
    QPushButton *pushButton_25;
    QLineEdit *lineEdit_45;
    QLabel *label_38;
    QLineEdit *lineEdit_46;
    QGroupBox *groupBox_23;
    QLabel *label_39;
    QPushButton *pushButton_26;
    QLineEdit *lineEdit_47;
    QLabel *label_40;
    QLineEdit *lineEdit_48;
    QMenuBar *menubar;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *VentanaConfigurar)
    {
        if (VentanaConfigurar->objectName().isEmpty())
            VentanaConfigurar->setObjectName(QString::fromUtf8("VentanaConfigurar"));
        VentanaConfigurar->resize(1524, 816);
        centralwidget = new QWidget(VentanaConfigurar);
        centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
        insertarPaquete = new QGroupBox(centralwidget);
        insertarPaquete->setObjectName(QString::fromUtf8("insertarPaquete"));
        insertarPaquete->setGeometry(QRect(10, 0, 331, 241));
        QFont font;
        font.setPointSize(15);
        insertarPaquete->setFont(font);
        insertarPaquete->setLayoutDirection(Qt::LeftToRight);
        insertarPaquete->setAlignment(Qt::AlignCenter);
        lineEdit = new QLineEdit(insertarPaquete);
        lineEdit->setObjectName(QString::fromUtf8("lineEdit"));
        lineEdit->setGeometry(QRect(180, 40, 121, 31));
        label = new QLabel(insertarPaquete);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(10, 40, 161, 31));
        label_2 = new QLabel(insertarPaquete);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(10, 90, 161, 31));
        lineEdit_2 = new QLineEdit(insertarPaquete);
        lineEdit_2->setObjectName(QString::fromUtf8("lineEdit_2"));
        lineEdit_2->setGeometry(QRect(180, 90, 121, 31));
        label_3 = new QLabel(insertarPaquete);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(10, 140, 161, 31));
        lineEdit_3 = new QLineEdit(insertarPaquete);
        lineEdit_3->setObjectName(QString::fromUtf8("lineEdit_3"));
        lineEdit_3->setGeometry(QRect(180, 140, 121, 31));
        pushButton = new QPushButton(insertarPaquete);
        pushButton->setObjectName(QString::fromUtf8("pushButton"));
        pushButton->setGeometry(QRect(100, 190, 121, 31));
        groupBox = new QGroupBox(centralwidget);
        groupBox->setObjectName(QString::fromUtf8("groupBox"));
        groupBox->setGeometry(QRect(0, 240, 341, 241));
        groupBox->setFont(font);
        groupBox->setAlignment(Qt::AlignCenter);
        label_4 = new QLabel(groupBox);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(70, 30, 261, 31));
        lineEdit_4 = new QLineEdit(groupBox);
        lineEdit_4->setObjectName(QString::fromUtf8("lineEdit_4"));
        lineEdit_4->setGeometry(QRect(110, 70, 121, 31));
        label_5 = new QLabel(groupBox);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(50, 110, 261, 31));
        lineEdit_5 = new QLineEdit(groupBox);
        lineEdit_5->setObjectName(QString::fromUtf8("lineEdit_5"));
        lineEdit_5->setGeometry(QRect(110, 150, 121, 31));
        pushButton_2 = new QPushButton(groupBox);
        pushButton_2->setObjectName(QString::fromUtf8("pushButton_2"));
        pushButton_2->setGeometry(QRect(130, 200, 80, 31));
        groupBox_2 = new QGroupBox(centralwidget);
        groupBox_2->setObjectName(QString::fromUtf8("groupBox_2"));
        groupBox_2->setGeometry(QRect(0, 480, 341, 301));
        QFont font1;
        font1.setPointSize(13);
        groupBox_2->setFont(font1);
        groupBox_2->setAlignment(Qt::AlignCenter);
        label_6 = new QLabel(groupBox_2);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(80, 30, 261, 31));
        lineEdit_6 = new QLineEdit(groupBox_2);
        lineEdit_6->setObjectName(QString::fromUtf8("lineEdit_6"));
        lineEdit_6->setGeometry(QRect(110, 70, 121, 31));
        label_7 = new QLabel(groupBox_2);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(40, 110, 291, 31));
        lineEdit_7 = new QLineEdit(groupBox_2);
        lineEdit_7->setObjectName(QString::fromUtf8("lineEdit_7"));
        lineEdit_7->setGeometry(QRect(110, 150, 121, 31));
        pushButton_3 = new QPushButton(groupBox_2);
        pushButton_3->setObjectName(QString::fromUtf8("pushButton_3"));
        pushButton_3->setGeometry(QRect(130, 260, 80, 31));
        label_8 = new QLabel(groupBox_2);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(60, 190, 291, 31));
        lineEdit_8 = new QLineEdit(groupBox_2);
        lineEdit_8->setObjectName(QString::fromUtf8("lineEdit_8"));
        lineEdit_8->setGeometry(QRect(110, 220, 121, 31));
        groupBox_3 = new QGroupBox(centralwidget);
        groupBox_3->setObjectName(QString::fromUtf8("groupBox_3"));
        groupBox_3->setGeometry(QRect(360, 0, 371, 261));
        groupBox_3->setFont(font1);
        groupBox_3->setAlignment(Qt::AlignCenter);
        label_9 = new QLabel(groupBox_3);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(10, 30, 161, 31));
        lineEdit_9 = new QLineEdit(groupBox_3);
        lineEdit_9->setObjectName(QString::fromUtf8("lineEdit_9"));
        lineEdit_9->setGeometry(QRect(20, 70, 121, 31));
        label_10 = new QLabel(groupBox_3);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(180, 30, 211, 31));
        pushButton_4 = new QPushButton(groupBox_3);
        pushButton_4->setObjectName(QString::fromUtf8("pushButton_4"));
        pushButton_4->setGeometry(QRect(140, 200, 80, 31));
        label_11 = new QLabel(groupBox_3);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(30, 120, 291, 31));
        lineEdit_11 = new QLineEdit(groupBox_3);
        lineEdit_11->setObjectName(QString::fromUtf8("lineEdit_11"));
        lineEdit_11->setGeometry(QRect(20, 160, 121, 31));
        lineEdit_12 = new QLineEdit(groupBox_3);
        lineEdit_12->setObjectName(QString::fromUtf8("lineEdit_12"));
        lineEdit_12->setGeometry(QRect(220, 70, 121, 31));
        lineEdit_13 = new QLineEdit(groupBox_3);
        lineEdit_13->setObjectName(QString::fromUtf8("lineEdit_13"));
        lineEdit_13->setGeometry(QRect(220, 160, 121, 31));
        label_12 = new QLabel(groupBox_3);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(230, 120, 131, 31));
        groupBox_4 = new QGroupBox(centralwidget);
        groupBox_4->setObjectName(QString::fromUtf8("groupBox_4"));
        groupBox_4->setGeometry(QRect(360, 270, 371, 251));
        groupBox_4->setFont(font1);
        groupBox_4->setAlignment(Qt::AlignCenter);
        label_13 = new QLabel(groupBox_4);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(10, 30, 161, 31));
        lineEdit_10 = new QLineEdit(groupBox_4);
        lineEdit_10->setObjectName(QString::fromUtf8("lineEdit_10"));
        lineEdit_10->setGeometry(QRect(20, 70, 121, 31));
        label_14 = new QLabel(groupBox_4);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(180, 30, 211, 31));
        pushButton_5 = new QPushButton(groupBox_4);
        pushButton_5->setObjectName(QString::fromUtf8("pushButton_5"));
        pushButton_5->setGeometry(QRect(140, 200, 80, 31));
        label_15 = new QLabel(groupBox_4);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setGeometry(QRect(30, 120, 291, 31));
        lineEdit_14 = new QLineEdit(groupBox_4);
        lineEdit_14->setObjectName(QString::fromUtf8("lineEdit_14"));
        lineEdit_14->setGeometry(QRect(20, 160, 121, 31));
        lineEdit_15 = new QLineEdit(groupBox_4);
        lineEdit_15->setObjectName(QString::fromUtf8("lineEdit_15"));
        lineEdit_15->setGeometry(QRect(220, 70, 121, 31));
        lineEdit_16 = new QLineEdit(groupBox_4);
        lineEdit_16->setObjectName(QString::fromUtf8("lineEdit_16"));
        lineEdit_16->setGeometry(QRect(220, 160, 121, 31));
        label_16 = new QLabel(groupBox_4);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setGeometry(QRect(220, 120, 121, 31));
        groupBox_5 = new QGroupBox(centralwidget);
        groupBox_5->setObjectName(QString::fromUtf8("groupBox_5"));
        groupBox_5->setGeometry(QRect(360, 530, 371, 251));
        groupBox_5->setFont(font1);
        groupBox_5->setAlignment(Qt::AlignCenter);
        label_17 = new QLabel(groupBox_5);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setGeometry(QRect(10, 30, 161, 31));
        lineEdit_17 = new QLineEdit(groupBox_5);
        lineEdit_17->setObjectName(QString::fromUtf8("lineEdit_17"));
        lineEdit_17->setGeometry(QRect(20, 70, 121, 31));
        label_18 = new QLabel(groupBox_5);
        label_18->setObjectName(QString::fromUtf8("label_18"));
        label_18->setGeometry(QRect(180, 30, 211, 31));
        pushButton_6 = new QPushButton(groupBox_5);
        pushButton_6->setObjectName(QString::fromUtf8("pushButton_6"));
        pushButton_6->setGeometry(QRect(140, 210, 80, 31));
        label_19 = new QLabel(groupBox_5);
        label_19->setObjectName(QString::fromUtf8("label_19"));
        label_19->setGeometry(QRect(30, 120, 291, 31));
        lineEdit_18 = new QLineEdit(groupBox_5);
        lineEdit_18->setObjectName(QString::fromUtf8("lineEdit_18"));
        lineEdit_18->setGeometry(QRect(20, 160, 121, 31));
        lineEdit_19 = new QLineEdit(groupBox_5);
        lineEdit_19->setObjectName(QString::fromUtf8("lineEdit_19"));
        lineEdit_19->setGeometry(QRect(220, 70, 121, 31));
        lineEdit_20 = new QLineEdit(groupBox_5);
        lineEdit_20->setObjectName(QString::fromUtf8("lineEdit_20"));
        lineEdit_20->setGeometry(QRect(220, 160, 121, 31));
        label_20 = new QLabel(groupBox_5);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setGeometry(QRect(220, 120, 131, 31));
        groupBox_6 = new QGroupBox(centralwidget);
        groupBox_6->setObjectName(QString::fromUtf8("groupBox_6"));
        groupBox_6->setGeometry(QRect(750, 0, 371, 131));
        groupBox_6->setFont(font1);
        groupBox_6->setAlignment(Qt::AlignCenter);
        label_21 = new QLabel(groupBox_6);
        label_21->setObjectName(QString::fromUtf8("label_21"));
        label_21->setGeometry(QRect(50, 30, 61, 31));
        lineEdit_21 = new QLineEdit(groupBox_6);
        lineEdit_21->setObjectName(QString::fromUtf8("lineEdit_21"));
        lineEdit_21->setGeometry(QRect(20, 70, 121, 31));
        pushButton_7 = new QPushButton(groupBox_6);
        pushButton_7->setObjectName(QString::fromUtf8("pushButton_7"));
        pushButton_7->setGeometry(QRect(209, 70, 101, 31));
        groupBox_7 = new QGroupBox(centralwidget);
        groupBox_7->setObjectName(QString::fromUtf8("groupBox_7"));
        groupBox_7->setGeometry(QRect(750, 130, 371, 121));
        groupBox_7->setFont(font1);
        groupBox_7->setAlignment(Qt::AlignCenter);
        label_22 = new QLabel(groupBox_7);
        label_22->setObjectName(QString::fromUtf8("label_22"));
        label_22->setGeometry(QRect(50, 30, 61, 31));
        lineEdit_22 = new QLineEdit(groupBox_7);
        lineEdit_22->setObjectName(QString::fromUtf8("lineEdit_22"));
        lineEdit_22->setGeometry(QRect(20, 70, 121, 31));
        pushButton_8 = new QPushButton(groupBox_7);
        pushButton_8->setObjectName(QString::fromUtf8("pushButton_8"));
        pushButton_8->setGeometry(QRect(209, 70, 101, 31));
        groupBox_8 = new QGroupBox(centralwidget);
        groupBox_8->setObjectName(QString::fromUtf8("groupBox_8"));
        groupBox_8->setGeometry(QRect(750, 250, 371, 141));
        groupBox_8->setFont(font1);
        groupBox_8->setAlignment(Qt::AlignCenter);
        label_24 = new QLabel(groupBox_8);
        label_24->setObjectName(QString::fromUtf8("label_24"));
        label_24->setGeometry(QRect(10, 30, 161, 31));
        lineEdit_24 = new QLineEdit(groupBox_8);
        lineEdit_24->setObjectName(QString::fromUtf8("lineEdit_24"));
        lineEdit_24->setGeometry(QRect(20, 70, 121, 31));
        label_25 = new QLabel(groupBox_8);
        label_25->setObjectName(QString::fromUtf8("label_25"));
        label_25->setGeometry(QRect(180, 30, 211, 31));
        pushButton_10 = new QPushButton(groupBox_8);
        pushButton_10->setObjectName(QString::fromUtf8("pushButton_10"));
        pushButton_10->setGeometry(QRect(140, 110, 80, 31));
        lineEdit_26 = new QLineEdit(groupBox_8);
        lineEdit_26->setObjectName(QString::fromUtf8("lineEdit_26"));
        lineEdit_26->setGeometry(QRect(210, 70, 121, 31));
        groupBox_9 = new QGroupBox(centralwidget);
        groupBox_9->setObjectName(QString::fromUtf8("groupBox_9"));
        groupBox_9->setGeometry(QRect(750, 390, 371, 121));
        groupBox_9->setFont(font1);
        groupBox_9->setAlignment(Qt::AlignCenter);
        label_26 = new QLabel(groupBox_9);
        label_26->setObjectName(QString::fromUtf8("label_26"));
        label_26->setGeometry(QRect(50, 30, 61, 31));
        lineEdit_25 = new QLineEdit(groupBox_9);
        lineEdit_25->setObjectName(QString::fromUtf8("lineEdit_25"));
        lineEdit_25->setGeometry(QRect(20, 70, 121, 31));
        pushButton_11 = new QPushButton(groupBox_9);
        pushButton_11->setObjectName(QString::fromUtf8("pushButton_11"));
        pushButton_11->setGeometry(QRect(209, 70, 91, 31));
        groupBox_10 = new QGroupBox(centralwidget);
        groupBox_10->setObjectName(QString::fromUtf8("groupBox_10"));
        groupBox_10->setGeometry(QRect(1140, 0, 371, 451));
        groupBox_10->setFont(font1);
        groupBox_10->setAlignment(Qt::AlignCenter);
        label_27 = new QLabel(groupBox_10);
        label_27->setObjectName(QString::fromUtf8("label_27"));
        label_27->setGeometry(QRect(40, 20, 161, 31));
        lineEdit_27 = new QLineEdit(groupBox_10);
        lineEdit_27->setObjectName(QString::fromUtf8("lineEdit_27"));
        lineEdit_27->setGeometry(QRect(50, 50, 121, 31));
        pushButton_12 = new QPushButton(groupBox_10);
        pushButton_12->setObjectName(QString::fromUtf8("pushButton_12"));
        pushButton_12->setGeometry(QRect(240, 50, 80, 24));
        groupBox_11 = new QGroupBox(groupBox_10);
        groupBox_11->setObjectName(QString::fromUtf8("groupBox_11"));
        groupBox_11->setGeometry(QRect(20, 90, 161, 121));
        QFont font2;
        font2.setPointSize(11);
        font2.setItalic(false);
        groupBox_11->setFont(font2);
        groupBox_11->setAlignment(Qt::AlignCenter);
        lineEdit_28 = new QLineEdit(groupBox_11);
        lineEdit_28->setObjectName(QString::fromUtf8("lineEdit_28"));
        lineEdit_28->setGeometry(QRect(10, 30, 71, 41));
        radioButton = new QRadioButton(groupBox_11);
        radioButton->setObjectName(QString::fromUtf8("radioButton"));
        radioButton->setGeometry(QRect(100, 40, 51, 22));
        pushButton_13 = new QPushButton(groupBox_11);
        pushButton_13->setObjectName(QString::fromUtf8("pushButton_13"));
        pushButton_13->setGeometry(QRect(50, 80, 61, 31));
        groupBox_12 = new QGroupBox(groupBox_10);
        groupBox_12->setObjectName(QString::fromUtf8("groupBox_12"));
        groupBox_12->setGeometry(QRect(200, 90, 161, 121));
        groupBox_12->setFont(font2);
        groupBox_12->setAlignment(Qt::AlignCenter);
        lineEdit_29 = new QLineEdit(groupBox_12);
        lineEdit_29->setObjectName(QString::fromUtf8("lineEdit_29"));
        lineEdit_29->setGeometry(QRect(10, 30, 71, 41));
        radioButton_2 = new QRadioButton(groupBox_12);
        radioButton_2->setObjectName(QString::fromUtf8("radioButton_2"));
        radioButton_2->setGeometry(QRect(100, 40, 51, 22));
        pushButton_14 = new QPushButton(groupBox_12);
        pushButton_14->setObjectName(QString::fromUtf8("pushButton_14"));
        pushButton_14->setGeometry(QRect(50, 80, 61, 31));
        groupBox_13 = new QGroupBox(groupBox_10);
        groupBox_13->setObjectName(QString::fromUtf8("groupBox_13"));
        groupBox_13->setGeometry(QRect(20, 210, 161, 121));
        groupBox_13->setFont(font2);
        groupBox_13->setAlignment(Qt::AlignCenter);
        lineEdit_30 = new QLineEdit(groupBox_13);
        lineEdit_30->setObjectName(QString::fromUtf8("lineEdit_30"));
        lineEdit_30->setGeometry(QRect(10, 30, 71, 41));
        radioButton_3 = new QRadioButton(groupBox_13);
        radioButton_3->setObjectName(QString::fromUtf8("radioButton_3"));
        radioButton_3->setGeometry(QRect(100, 20, 51, 22));
        pushButton_15 = new QPushButton(groupBox_13);
        pushButton_15->setObjectName(QString::fromUtf8("pushButton_15"));
        pushButton_15->setGeometry(QRect(50, 80, 61, 31));
        radioButton_4 = new QRadioButton(groupBox_13);
        radioButton_4->setObjectName(QString::fromUtf8("radioButton_4"));
        radioButton_4->setGeometry(QRect(100, 50, 99, 22));
        groupBox_14 = new QGroupBox(groupBox_10);
        groupBox_14->setObjectName(QString::fromUtf8("groupBox_14"));
        groupBox_14->setGeometry(QRect(200, 210, 161, 121));
        groupBox_14->setFont(font2);
        groupBox_14->setAlignment(Qt::AlignCenter);
        lineEdit_31 = new QLineEdit(groupBox_14);
        lineEdit_31->setObjectName(QString::fromUtf8("lineEdit_31"));
        lineEdit_31->setGeometry(QRect(10, 30, 71, 41));
        radioButton_5 = new QRadioButton(groupBox_14);
        radioButton_5->setObjectName(QString::fromUtf8("radioButton_5"));
        radioButton_5->setGeometry(QRect(100, 20, 51, 22));
        pushButton_16 = new QPushButton(groupBox_14);
        pushButton_16->setObjectName(QString::fromUtf8("pushButton_16"));
        pushButton_16->setGeometry(QRect(50, 80, 61, 31));
        radioButton_6 = new QRadioButton(groupBox_14);
        radioButton_6->setObjectName(QString::fromUtf8("radioButton_6"));
        radioButton_6->setGeometry(QRect(100, 50, 99, 22));
        groupBox_15 = new QGroupBox(groupBox_10);
        groupBox_15->setObjectName(QString::fromUtf8("groupBox_15"));
        groupBox_15->setGeometry(QRect(20, 330, 161, 121));
        groupBox_15->setFont(font2);
        groupBox_15->setAlignment(Qt::AlignCenter);
        lineEdit_33 = new QLineEdit(groupBox_15);
        lineEdit_33->setObjectName(QString::fromUtf8("lineEdit_33"));
        lineEdit_33->setGeometry(QRect(10, 30, 71, 41));
        radioButton_9 = new QRadioButton(groupBox_15);
        radioButton_9->setObjectName(QString::fromUtf8("radioButton_9"));
        radioButton_9->setGeometry(QRect(100, 20, 51, 22));
        pushButton_18 = new QPushButton(groupBox_15);
        pushButton_18->setObjectName(QString::fromUtf8("pushButton_18"));
        pushButton_18->setGeometry(QRect(50, 80, 61, 31));
        radioButton_10 = new QRadioButton(groupBox_15);
        radioButton_10->setObjectName(QString::fromUtf8("radioButton_10"));
        radioButton_10->setGeometry(QRect(100, 50, 99, 22));
        groupBox_16 = new QGroupBox(groupBox_10);
        groupBox_16->setObjectName(QString::fromUtf8("groupBox_16"));
        groupBox_16->setGeometry(QRect(200, 330, 161, 121));
        groupBox_16->setFont(font2);
        groupBox_16->setAlignment(Qt::AlignCenter);
        lineEdit_34 = new QLineEdit(groupBox_16);
        lineEdit_34->setObjectName(QString::fromUtf8("lineEdit_34"));
        lineEdit_34->setGeometry(QRect(10, 30, 71, 41));
        radioButton_11 = new QRadioButton(groupBox_16);
        radioButton_11->setObjectName(QString::fromUtf8("radioButton_11"));
        radioButton_11->setGeometry(QRect(100, 20, 51, 22));
        pushButton_19 = new QPushButton(groupBox_16);
        pushButton_19->setObjectName(QString::fromUtf8("pushButton_19"));
        pushButton_19->setGeometry(QRect(50, 80, 61, 31));
        radioButton_12 = new QRadioButton(groupBox_16);
        radioButton_12->setObjectName(QString::fromUtf8("radioButton_12"));
        radioButton_12->setGeometry(QRect(100, 50, 99, 22));
        groupBox_17 = new QGroupBox(centralwidget);
        groupBox_17->setObjectName(QString::fromUtf8("groupBox_17"));
        groupBox_17->setGeometry(QRect(750, 520, 371, 121));
        groupBox_17->setFont(font1);
        groupBox_17->setAlignment(Qt::AlignCenter);
        label_28 = new QLabel(groupBox_17);
        label_28->setObjectName(QString::fromUtf8("label_28"));
        label_28->setGeometry(QRect(50, 30, 61, 31));
        lineEdit_35 = new QLineEdit(groupBox_17);
        lineEdit_35->setObjectName(QString::fromUtf8("lineEdit_35"));
        lineEdit_35->setGeometry(QRect(20, 70, 121, 31));
        pushButton_20 = new QPushButton(groupBox_17);
        pushButton_20->setObjectName(QString::fromUtf8("pushButton_20"));
        pushButton_20->setGeometry(QRect(209, 70, 91, 31));
        groupBox_18 = new QGroupBox(centralwidget);
        groupBox_18->setObjectName(QString::fromUtf8("groupBox_18"));
        groupBox_18->setGeometry(QRect(750, 650, 371, 131));
        groupBox_18->setFont(font1);
        groupBox_18->setAlignment(Qt::AlignCenter);
        label_29 = new QLabel(groupBox_18);
        label_29->setObjectName(QString::fromUtf8("label_29"));
        label_29->setGeometry(QRect(20, 30, 81, 31));
        lineEdit_36 = new QLineEdit(groupBox_18);
        lineEdit_36->setObjectName(QString::fromUtf8("lineEdit_36"));
        lineEdit_36->setGeometry(QRect(20, 70, 81, 31));
        pushButton_21 = new QPushButton(groupBox_18);
        pushButton_21->setObjectName(QString::fromUtf8("pushButton_21"));
        pushButton_21->setGeometry(QRect(150, 90, 80, 31));
        lineEdit_37 = new QLineEdit(groupBox_18);
        lineEdit_37->setObjectName(QString::fromUtf8("lineEdit_37"));
        lineEdit_37->setGeometry(QRect(270, 70, 81, 31));
        label_30 = new QLabel(groupBox_18);
        label_30->setObjectName(QString::fromUtf8("label_30"));
        label_30->setGeometry(QRect(270, 30, 81, 31));
        groupBox_22 = new QGroupBox(centralwidget);
        groupBox_22->setObjectName(QString::fromUtf8("groupBox_22"));
        groupBox_22->setGeometry(QRect(1140, 500, 371, 101));
        groupBox_22->setFont(font1);
        groupBox_22->setAlignment(Qt::AlignCenter);
        label_37 = new QLabel(groupBox_22);
        label_37->setObjectName(QString::fromUtf8("label_37"));
        label_37->setGeometry(QRect(30, 10, 131, 41));
        pushButton_25 = new QPushButton(groupBox_22);
        pushButton_25->setObjectName(QString::fromUtf8("pushButton_25"));
        pushButton_25->setGeometry(QRect(150, 50, 71, 31));
        lineEdit_45 = new QLineEdit(groupBox_22);
        lineEdit_45->setObjectName(QString::fromUtf8("lineEdit_45"));
        lineEdit_45->setGeometry(QRect(270, 50, 81, 21));
        label_38 = new QLabel(groupBox_22);
        label_38->setObjectName(QString::fromUtf8("label_38"));
        label_38->setGeometry(QRect(280, 10, 161, 41));
        lineEdit_46 = new QLineEdit(groupBox_22);
        lineEdit_46->setObjectName(QString::fromUtf8("lineEdit_46"));
        lineEdit_46->setGeometry(QRect(20, 50, 81, 21));
        groupBox_23 = new QGroupBox(centralwidget);
        groupBox_23->setObjectName(QString::fromUtf8("groupBox_23"));
        groupBox_23->setGeometry(QRect(1140, 660, 371, 111));
        groupBox_23->setFont(font1);
        groupBox_23->setAlignment(Qt::AlignCenter);
        label_39 = new QLabel(groupBox_23);
        label_39->setObjectName(QString::fromUtf8("label_39"));
        label_39->setGeometry(QRect(30, 20, 131, 41));
        pushButton_26 = new QPushButton(groupBox_23);
        pushButton_26->setObjectName(QString::fromUtf8("pushButton_26"));
        pushButton_26->setGeometry(QRect(150, 80, 71, 31));
        lineEdit_47 = new QLineEdit(groupBox_23);
        lineEdit_47->setObjectName(QString::fromUtf8("lineEdit_47"));
        lineEdit_47->setGeometry(QRect(270, 60, 81, 21));
        label_40 = new QLabel(groupBox_23);
        label_40->setObjectName(QString::fromUtf8("label_40"));
        label_40->setGeometry(QRect(280, 20, 161, 41));
        lineEdit_48 = new QLineEdit(groupBox_23);
        lineEdit_48->setObjectName(QString::fromUtf8("lineEdit_48"));
        lineEdit_48->setGeometry(QRect(20, 60, 81, 21));
        VentanaConfigurar->setCentralWidget(centralwidget);
        menubar = new QMenuBar(VentanaConfigurar);
        menubar->setObjectName(QString::fromUtf8("menubar"));
        menubar->setGeometry(QRect(0, 0, 1524, 21));
        VentanaConfigurar->setMenuBar(menubar);
        statusbar = new QStatusBar(VentanaConfigurar);
        statusbar->setObjectName(QString::fromUtf8("statusbar"));
        VentanaConfigurar->setStatusBar(statusbar);

        retranslateUi(VentanaConfigurar);

        QMetaObject::connectSlotsByName(VentanaConfigurar);
    } // setupUi

    void retranslateUi(QMainWindow *VentanaConfigurar)
    {
        VentanaConfigurar->setWindowTitle(QCoreApplication::translate("VentanaConfigurar", "MainWindow", nullptr));
        insertarPaquete->setTitle(QCoreApplication::translate("VentanaConfigurar", "Insertar Paquete", nullptr));
        lineEdit->setText(QString());
        label->setText(QCoreApplication::translate("VentanaConfigurar", "Nombre del paquete:", nullptr));
        label_2->setText(QCoreApplication::translate("VentanaConfigurar", "Cantidad de galletas: ", nullptr));
        lineEdit_2->setText(QCoreApplication::translate("VentanaConfigurar", "0", nullptr));
        label_3->setText(QCoreApplication::translate("VentanaConfigurar", "Cantidad de paquetes: ", nullptr));
        lineEdit_3->setText(QCoreApplication::translate("VentanaConfigurar", "0", nullptr));
        pushButton->setText(QCoreApplication::translate("VentanaConfigurar", "Insertar", nullptr));
        groupBox->setTitle(QCoreApplication::translate("VentanaConfigurar", "Receta", nullptr));
        label_4->setText(QCoreApplication::translate("VentanaConfigurar", "Cantidad de masa por galleta: ", nullptr));
        lineEdit_4->setText(QCoreApplication::translate("VentanaConfigurar", "0", nullptr));
        label_5->setText(QCoreApplication::translate("VentanaConfigurar", "Cantidad de chocolate por galleta: ", nullptr));
        lineEdit_5->setText(QCoreApplication::translate("VentanaConfigurar", "0", nullptr));
        pushButton_2->setText(QCoreApplication::translate("VentanaConfigurar", "Insertar", nullptr));
        groupBox_2->setTitle(QCoreApplication::translate("VentanaConfigurar", "Carrito", nullptr));
        label_6->setText(QCoreApplication::translate("VentanaConfigurar", "Tiempo de viaje por env\303\255o:", nullptr));
        lineEdit_6->setText(QCoreApplication::translate("VentanaConfigurar", "0", nullptr));
        label_7->setText(QCoreApplication::translate("VentanaConfigurar", "Capacidad de transporte de chocolate:", nullptr));
        lineEdit_7->setText(QCoreApplication::translate("VentanaConfigurar", "0", nullptr));
        pushButton_3->setText(QCoreApplication::translate("VentanaConfigurar", "Insertar", nullptr));
        label_8->setText(QCoreApplication::translate("VentanaConfigurar", "Capacidad de transporte de masa:", nullptr));
        lineEdit_8->setText(QCoreApplication::translate("VentanaConfigurar", "0", nullptr));
        groupBox_3->setTitle(QCoreApplication::translate("VentanaConfigurar", "M\303\241quina de Masa 1", nullptr));
        label_9->setText(QCoreApplication::translate("VentanaConfigurar", "Tiempo de producci\303\263n:", nullptr));
        lineEdit_9->setText(QCoreApplication::translate("VentanaConfigurar", "0", nullptr));
        label_10->setText(QCoreApplication::translate("VentanaConfigurar", "Cantidad producida por tiempo:", nullptr));
        pushButton_4->setText(QCoreApplication::translate("VentanaConfigurar", "Insertar", nullptr));
        label_11->setText(QCoreApplication::translate("VentanaConfigurar", "Cantidad m\303\255nima:", nullptr));
        lineEdit_11->setText(QCoreApplication::translate("VentanaConfigurar", "0", nullptr));
        lineEdit_12->setText(QCoreApplication::translate("VentanaConfigurar", "0", nullptr));
        lineEdit_13->setText(QCoreApplication::translate("VentanaConfigurar", "0", nullptr));
        label_12->setText(QCoreApplication::translate("VentanaConfigurar", "Cantidad  m\303\241xima:", nullptr));
        groupBox_4->setTitle(QCoreApplication::translate("VentanaConfigurar", "M\303\241quina de Masa 2", nullptr));
        label_13->setText(QCoreApplication::translate("VentanaConfigurar", "Tiempo de producci\303\263n:", nullptr));
        lineEdit_10->setText(QCoreApplication::translate("VentanaConfigurar", "0", nullptr));
        label_14->setText(QCoreApplication::translate("VentanaConfigurar", "Cantidad producida por tiempo:", nullptr));
        pushButton_5->setText(QCoreApplication::translate("VentanaConfigurar", "Insertar", nullptr));
        label_15->setText(QCoreApplication::translate("VentanaConfigurar", "Cantidad m\303\255nima:", nullptr));
        lineEdit_14->setText(QCoreApplication::translate("VentanaConfigurar", "0", nullptr));
        lineEdit_15->setText(QCoreApplication::translate("VentanaConfigurar", "0", nullptr));
        lineEdit_16->setText(QCoreApplication::translate("VentanaConfigurar", "0", nullptr));
        label_16->setText(QCoreApplication::translate("VentanaConfigurar", "Cantidad  m\303\241xima:", nullptr));
        groupBox_5->setTitle(QCoreApplication::translate("VentanaConfigurar", "M\303\241quina de Chocolate", nullptr));
        label_17->setText(QCoreApplication::translate("VentanaConfigurar", "Tiempo de producci\303\263n:", nullptr));
        lineEdit_17->setText(QCoreApplication::translate("VentanaConfigurar", "0", nullptr));
        label_18->setText(QCoreApplication::translate("VentanaConfigurar", "Cantidad producida por tiempo:", nullptr));
        pushButton_6->setText(QCoreApplication::translate("VentanaConfigurar", "Insertar", nullptr));
        label_19->setText(QCoreApplication::translate("VentanaConfigurar", "Cantidad m\303\255nima:", nullptr));
        lineEdit_18->setText(QCoreApplication::translate("VentanaConfigurar", "0", nullptr));
        lineEdit_19->setText(QCoreApplication::translate("VentanaConfigurar", "0", nullptr));
        lineEdit_20->setText(QCoreApplication::translate("VentanaConfigurar", "0", nullptr));
        label_20->setText(QCoreApplication::translate("VentanaConfigurar", "Cantidad  m\303\241xima:", nullptr));
        groupBox_6->setTitle(QCoreApplication::translate("VentanaConfigurar", "Banda Transportadora de Masa", nullptr));
        label_21->setText(QCoreApplication::translate("VentanaConfigurar", "M\303\241ximo:", nullptr));
        lineEdit_21->setText(QCoreApplication::translate("VentanaConfigurar", "0", nullptr));
        pushButton_7->setText(QCoreApplication::translate("VentanaConfigurar", "Insertar", nullptr));
        groupBox_7->setTitle(QCoreApplication::translate("VentanaConfigurar", "Banda Transportadora de Chocolate", nullptr));
        label_22->setText(QCoreApplication::translate("VentanaConfigurar", "M\303\241ximo:", nullptr));
        lineEdit_22->setText(QCoreApplication::translate("VentanaConfigurar", "0", nullptr));
        pushButton_8->setText(QCoreApplication::translate("VentanaConfigurar", "Insertar", nullptr));
        groupBox_8->setTitle(QCoreApplication::translate("VentanaConfigurar", "M\303\241quina Ensambladora", nullptr));
        label_24->setText(QCoreApplication::translate("VentanaConfigurar", "Tiempo de producci\303\263n:", nullptr));
        lineEdit_24->setText(QCoreApplication::translate("VentanaConfigurar", "0", nullptr));
        label_25->setText(QCoreApplication::translate("VentanaConfigurar", "Cantidad producida por tiempo:", nullptr));
        pushButton_10->setText(QCoreApplication::translate("VentanaConfigurar", "Insertar", nullptr));
        lineEdit_26->setText(QCoreApplication::translate("VentanaConfigurar", "0", nullptr));
        groupBox_9->setTitle(QCoreApplication::translate("VentanaConfigurar", "Banda Transportadora de galletas por hornear", nullptr));
        label_26->setText(QCoreApplication::translate("VentanaConfigurar", "M\303\241ximo:", nullptr));
        lineEdit_25->setText(QCoreApplication::translate("VentanaConfigurar", "0", nullptr));
        pushButton_11->setText(QCoreApplication::translate("VentanaConfigurar", "Insertar", nullptr));
        groupBox_10->setTitle(QCoreApplication::translate("VentanaConfigurar", "Horno", nullptr));
        label_27->setText(QCoreApplication::translate("VentanaConfigurar", "Tiempo de horneado: ", nullptr));
        lineEdit_27->setText(QCoreApplication::translate("VentanaConfigurar", "0", nullptr));
        pushButton_12->setText(QCoreApplication::translate("VentanaConfigurar", "Insertar", nullptr));
        groupBox_11->setTitle(QCoreApplication::translate("VentanaConfigurar", "Bandeja 1", nullptr));
        lineEdit_28->setText(QCoreApplication::translate("VentanaConfigurar", " Capacidad", nullptr));
        radioButton->setText(QCoreApplication::translate("VentanaConfigurar", "ON", nullptr));
        pushButton_13->setText(QCoreApplication::translate("VentanaConfigurar", "\342\210\232", nullptr));
        groupBox_12->setTitle(QCoreApplication::translate("VentanaConfigurar", "Bandeja 2", nullptr));
        lineEdit_29->setText(QCoreApplication::translate("VentanaConfigurar", " Capacidad", nullptr));
        radioButton_2->setText(QCoreApplication::translate("VentanaConfigurar", "ON", nullptr));
        pushButton_14->setText(QCoreApplication::translate("VentanaConfigurar", "\342\210\232", nullptr));
        groupBox_13->setTitle(QCoreApplication::translate("VentanaConfigurar", "Bandeja 3", nullptr));
        lineEdit_30->setText(QCoreApplication::translate("VentanaConfigurar", " Capacidad", nullptr));
        radioButton_3->setText(QCoreApplication::translate("VentanaConfigurar", "ON", nullptr));
        pushButton_15->setText(QCoreApplication::translate("VentanaConfigurar", "\342\210\232", nullptr));
        radioButton_4->setText(QCoreApplication::translate("VentanaConfigurar", "OFF", nullptr));
        groupBox_14->setTitle(QCoreApplication::translate("VentanaConfigurar", "Bandeja 4", nullptr));
        lineEdit_31->setText(QCoreApplication::translate("VentanaConfigurar", " Capacidad", nullptr));
        radioButton_5->setText(QCoreApplication::translate("VentanaConfigurar", "ON", nullptr));
        pushButton_16->setText(QCoreApplication::translate("VentanaConfigurar", "\342\210\232", nullptr));
        radioButton_6->setText(QCoreApplication::translate("VentanaConfigurar", "OFF", nullptr));
        groupBox_15->setTitle(QCoreApplication::translate("VentanaConfigurar", "Bandeja 5", nullptr));
        lineEdit_33->setText(QCoreApplication::translate("VentanaConfigurar", " Capacidad", nullptr));
        radioButton_9->setText(QCoreApplication::translate("VentanaConfigurar", "ON", nullptr));
        pushButton_18->setText(QCoreApplication::translate("VentanaConfigurar", "\342\210\232", nullptr));
        radioButton_10->setText(QCoreApplication::translate("VentanaConfigurar", "OFF", nullptr));
        groupBox_16->setTitle(QCoreApplication::translate("VentanaConfigurar", "Bandeja 6", nullptr));
        lineEdit_34->setText(QCoreApplication::translate("VentanaConfigurar", " Capacidad", nullptr));
        radioButton_11->setText(QCoreApplication::translate("VentanaConfigurar", "ON", nullptr));
        pushButton_19->setText(QCoreApplication::translate("VentanaConfigurar", "\342\210\232", nullptr));
        radioButton_12->setText(QCoreApplication::translate("VentanaConfigurar", "OFF", nullptr));
        groupBox_17->setTitle(QCoreApplication::translate("VentanaConfigurar", "Banda Transportadora de galletas horneadas a supervisar", nullptr));
        label_28->setText(QCoreApplication::translate("VentanaConfigurar", "M\303\241ximo:", nullptr));
        lineEdit_35->setText(QCoreApplication::translate("VentanaConfigurar", "0", nullptr));
        pushButton_20->setText(QCoreApplication::translate("VentanaConfigurar", "Insertar", nullptr));
        groupBox_18->setTitle(QCoreApplication::translate("VentanaConfigurar", "Probabilidad de los supervisores", nullptr));
        label_29->setText(QCoreApplication::translate("VentanaConfigurar", "Supervisor 1", nullptr));
        lineEdit_36->setText(QCoreApplication::translate("VentanaConfigurar", "0", nullptr));
        pushButton_21->setText(QCoreApplication::translate("VentanaConfigurar", "Insertar", nullptr));
        lineEdit_37->setText(QCoreApplication::translate("VentanaConfigurar", "0", nullptr));
        label_30->setText(QCoreApplication::translate("VentanaConfigurar", "Supervisor 2", nullptr));
        groupBox_22->setTitle(QCoreApplication::translate("VentanaConfigurar", "M\303\241quina Empacadora", nullptr));
        label_37->setText(QCoreApplication::translate("VentanaConfigurar", "Tiempo:", nullptr));
        pushButton_25->setText(QCoreApplication::translate("VentanaConfigurar", "Insertar", nullptr));
        lineEdit_45->setText(QCoreApplication::translate("VentanaConfigurar", "0", nullptr));
        label_38->setText(QCoreApplication::translate("VentanaConfigurar", "Capacidad:", nullptr));
        lineEdit_46->setText(QCoreApplication::translate("VentanaConfigurar", "0", nullptr));
        groupBox_23->setTitle(QCoreApplication::translate("VentanaConfigurar", "Transportadores", nullptr));
        label_39->setText(QCoreApplication::translate("VentanaConfigurar", "Tiempo:", nullptr));
        pushButton_26->setText(QCoreApplication::translate("VentanaConfigurar", "Insertar", nullptr));
        lineEdit_47->setText(QCoreApplication::translate("VentanaConfigurar", "0", nullptr));
        label_40->setText(QCoreApplication::translate("VentanaConfigurar", "Capacidad:", nullptr));
        lineEdit_48->setText(QCoreApplication::translate("VentanaConfigurar", "0", nullptr));
    } // retranslateUi

};

namespace Ui {
    class VentanaConfigurar: public Ui_VentanaConfigurar {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_VENTANACONFIGURAR_H
