/********************************************************************************
** Form generated from reading UI file 'ventanaconfigurar.ui'
**
** Created by: Qt User Interface Compiler version 6.1.3
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_VENTANACONFIGURAR_H
#define UI_VENTANACONFIGURAR_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_VentanaConfigurar
{
public:
    QWidget *centralwidget;
    QGroupBox *insertarPaquete;
    QLineEdit *txt_InsNom;
    QLabel *label;
    QLabel *label_2;
    QLineEdit *txt_InsCntGalletas;
    QLabel *label_3;
    QLineEdit *txt_InsCntPaq;
    QPushButton *btn_InsIns;
    QGroupBox *groupBox;
    QLabel *label_4;
    QLineEdit *txt_RecCntMasaGall;
    QLabel *label_5;
    QLineEdit *txt_RecCntChocoGall;
    QPushButton *btn_RecIns;
    QGroupBox *groupBox_2;
    QLabel *label_6;
    QLineEdit *txt_CarTmpXEnv;
    QLabel *label_7;
    QLineEdit *txt_CarTransChoco;
    QPushButton *btn_CarIns;
    QLabel *label_8;
    QLineEdit *txt_CarTransMasa;
    QGroupBox *groupBox_3;
    QLabel *label_9;
    QLineEdit *txt_maq1TmpProd;
    QLabel *label_10;
    QPushButton *btn_maq1Ins;
    QLabel *label_11;
    QLineEdit *txt_maq1CntMin;
    QLineEdit *txt_maq1CntProdTiempo;
    QLineEdit *txt_maq1CntMax;
    QLabel *label_12;
    QGroupBox *groupBox_4;
    QLabel *label_13;
    QLineEdit *txt_maq2TmpProd;
    QLabel *label_14;
    QPushButton *btn_maq2Ins;
    QLineEdit *txt_maq2CntMin;
    QLineEdit *txt_maq2CntProdTiempo;
    QLineEdit *txt_maq2CntMax;
    QLabel *label_16;
    QLabel *label_23;
    QGroupBox *groupBox_5;
    QLabel *label_17;
    QLineEdit *txt_maqChTmpProd;
    QLabel *label_18;
    QPushButton *btn_maqChIns;
    QLabel *label_19;
    QLineEdit *txt_maqChCntMin;
    QLineEdit *txt_maqChCntProdTiempo;
    QLineEdit *txt_maqChCntMax;
    QLabel *label_20;
    QGroupBox *groupBox_6;
    QLabel *label_21;
    QLineEdit *txt_BTMMax;
    QPushButton *btn_BTMIns;
    QGroupBox *groupBox_7;
    QLabel *label_22;
    QLineEdit *txt_BTChMax;
    QPushButton *btn_BTChIns;
    QGroupBox *groupBox_8;
    QLabel *label_24;
    QLineEdit *txt_maqEmsTmpProd;
    QLabel *label_25;
    QPushButton *btn_maqEmsIns;
    QLineEdit *txt_maqEmsCntProdXTiemp;
    QGroupBox *groupBox_9;
    QLabel *label_26;
    QLineEdit *txt_BTEmsHorMax;
    QPushButton *btn_BTEmsHorIns;
    QGroupBox *groupBox_10;
    QLabel *label_27;
    QLineEdit *txt_HorTmpHorneado;
    QPushButton *btn_HorIns;
    QGroupBox *groupBox_11;
    QLineEdit *txt_bnd1Cap;
    QRadioButton *rBtn_bnd1On;
    QPushButton *btn_bnd1Ins;
    QGroupBox *groupBox_12;
    QLineEdit *txt_bnd2Cap;
    QRadioButton *rBtn_bnd2On;
    QPushButton *btn_bnd2Ins;
    QGroupBox *groupBox_13;
    QLineEdit *txt_bnd3Cap;
    QRadioButton *rBtn_bnd3On;
    QPushButton *btn_bnd3Ins;
    QRadioButton *rBtn_bnd3Off;
    QGroupBox *groupBox_14;
    QLineEdit *txt_bnd4Cap;
    QRadioButton *rBtn_bnd4On;
    QPushButton *btn_bnd4Ins;
    QRadioButton *rBtn_bnd4Off;
    QGroupBox *groupBox_15;
    QLineEdit *txt_bnd5Cap;
    QRadioButton *rBtn_bnd5On;
    QPushButton *btn_bnd5Ins;
    QRadioButton *rBtn_bnd5Off;
    QGroupBox *groupBox_16;
    QLineEdit *txt_bnd6Cap;
    QRadioButton *rBtn_bnd6On;
    QPushButton *btn_bnd6Ins;
    QRadioButton *rBtn_bnd6Off;
    QGroupBox *groupBox_17;
    QLabel *label_28;
    QLineEdit *txt_BTHorSupMax;
    QPushButton *btn_BTHorSupIns;
    QGroupBox *groupBox_18;
    QLabel *label_29;
    QLineEdit *txt_Sup1Prob;
    QPushButton *btn_SupIns;
    QLineEdit *txt_Sup2Prob;
    QLabel *label_30;
    QGroupBox *groupBox_22;
    QPushButton *btn_maqEmpIns;
    QLineEdit *txt_maqEmpCap;
    QLineEdit *txt_maqEmpTmp;
    QLabel *label_40;
    QLabel *txt_transCap_3;
    QGroupBox *groupBox_23;
    QLabel *label_39;
    QLineEdit *txt_transCap_2;
    QLabel *txt_transCap;
    QLineEdit *txt_transTmp;
    QPushButton *btn_transIns;
    QMenuBar *menubar;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *VentanaConfigurar)
    {
        if (VentanaConfigurar->objectName().isEmpty())
            VentanaConfigurar->setObjectName(QString::fromUtf8("VentanaConfigurar"));
        VentanaConfigurar->resize(1524, 816);
        VentanaConfigurar->setCursor(QCursor(Qt::SizeAllCursor));
        VentanaConfigurar->setStyleSheet(QString::fromUtf8("\n"
"background-color: rgb(84, 43, 20)"));
        centralwidget = new QWidget(VentanaConfigurar);
        centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
        insertarPaquete = new QGroupBox(centralwidget);
        insertarPaquete->setObjectName(QString::fromUtf8("insertarPaquete"));
        insertarPaquete->setGeometry(QRect(10, 0, 331, 241));
        QFont font;
        font.setPointSize(15);
        font.setBold(true);
        font.setUnderline(true);
        insertarPaquete->setFont(font);
        insertarPaquete->setLayoutDirection(Qt::LeftToRight);
        insertarPaquete->setAlignment(Qt::AlignCenter);
        txt_InsNom = new QLineEdit(insertarPaquete);
        txt_InsNom->setObjectName(QString::fromUtf8("txt_InsNom"));
        txt_InsNom->setGeometry(QRect(180, 40, 121, 31));
        label = new QLabel(insertarPaquete);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(10, 40, 141, 31));
        label_2 = new QLabel(insertarPaquete);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(10, 90, 141, 31));
        txt_InsCntGalletas = new QLineEdit(insertarPaquete);
        txt_InsCntGalletas->setObjectName(QString::fromUtf8("txt_InsCntGalletas"));
        txt_InsCntGalletas->setGeometry(QRect(180, 90, 121, 31));
        label_3 = new QLabel(insertarPaquete);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(10, 140, 141, 31));
        txt_InsCntPaq = new QLineEdit(insertarPaquete);
        txt_InsCntPaq->setObjectName(QString::fromUtf8("txt_InsCntPaq"));
        txt_InsCntPaq->setGeometry(QRect(180, 140, 121, 31));
        btn_InsIns = new QPushButton(insertarPaquete);
        btn_InsIns->setObjectName(QString::fromUtf8("btn_InsIns"));
        btn_InsIns->setGeometry(QRect(100, 190, 121, 31));
        groupBox = new QGroupBox(centralwidget);
        groupBox->setObjectName(QString::fromUtf8("groupBox"));
        groupBox->setGeometry(QRect(10, 240, 331, 241));
        groupBox->setFont(font);
        groupBox->setAlignment(Qt::AlignCenter);
        label_4 = new QLabel(groupBox);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(70, 30, 191, 31));
        txt_RecCntMasaGall = new QLineEdit(groupBox);
        txt_RecCntMasaGall->setObjectName(QString::fromUtf8("txt_RecCntMasaGall"));
        txt_RecCntMasaGall->setGeometry(QRect(110, 70, 121, 31));
        label_5 = new QLabel(groupBox);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(50, 110, 211, 31));
        txt_RecCntChocoGall = new QLineEdit(groupBox);
        txt_RecCntChocoGall->setObjectName(QString::fromUtf8("txt_RecCntChocoGall"));
        txt_RecCntChocoGall->setGeometry(QRect(110, 150, 121, 31));
        btn_RecIns = new QPushButton(groupBox);
        btn_RecIns->setObjectName(QString::fromUtf8("btn_RecIns"));
        btn_RecIns->setGeometry(QRect(130, 200, 80, 31));
        groupBox_2 = new QGroupBox(centralwidget);
        groupBox_2->setObjectName(QString::fromUtf8("groupBox_2"));
        groupBox_2->setGeometry(QRect(10, 480, 331, 301));
        QFont font1;
        font1.setPointSize(13);
        groupBox_2->setFont(font1);
        groupBox_2->setAlignment(Qt::AlignCenter);
        label_6 = new QLabel(groupBox_2);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(80, 30, 171, 31));
        txt_CarTmpXEnv = new QLineEdit(groupBox_2);
        txt_CarTmpXEnv->setObjectName(QString::fromUtf8("txt_CarTmpXEnv"));
        txt_CarTmpXEnv->setGeometry(QRect(110, 70, 121, 31));
        label_7 = new QLabel(groupBox_2);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(40, 110, 241, 31));
        txt_CarTransChoco = new QLineEdit(groupBox_2);
        txt_CarTransChoco->setObjectName(QString::fromUtf8("txt_CarTransChoco"));
        txt_CarTransChoco->setGeometry(QRect(110, 150, 121, 31));
        btn_CarIns = new QPushButton(groupBox_2);
        btn_CarIns->setObjectName(QString::fromUtf8("btn_CarIns"));
        btn_CarIns->setGeometry(QRect(130, 260, 80, 31));
        label_8 = new QLabel(groupBox_2);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(60, 190, 221, 31));
        txt_CarTransMasa = new QLineEdit(groupBox_2);
        txt_CarTransMasa->setObjectName(QString::fromUtf8("txt_CarTransMasa"));
        txt_CarTransMasa->setGeometry(QRect(110, 220, 121, 31));
        groupBox_3 = new QGroupBox(centralwidget);
        groupBox_3->setObjectName(QString::fromUtf8("groupBox_3"));
        groupBox_3->setGeometry(QRect(360, 0, 371, 261));
        groupBox_3->setFont(font1);
        groupBox_3->setAlignment(Qt::AlignCenter);
        label_9 = new QLabel(groupBox_3);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(10, 30, 141, 31));
        txt_maq1TmpProd = new QLineEdit(groupBox_3);
        txt_maq1TmpProd->setObjectName(QString::fromUtf8("txt_maq1TmpProd"));
        txt_maq1TmpProd->setGeometry(QRect(20, 70, 121, 31));
        label_10 = new QLabel(groupBox_3);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(210, 30, 141, 31));
        btn_maq1Ins = new QPushButton(groupBox_3);
        btn_maq1Ins->setObjectName(QString::fromUtf8("btn_maq1Ins"));
        btn_maq1Ins->setGeometry(QRect(140, 200, 80, 31));
        label_11 = new QLabel(groupBox_3);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(20, 120, 121, 31));
        txt_maq1CntMin = new QLineEdit(groupBox_3);
        txt_maq1CntMin->setObjectName(QString::fromUtf8("txt_maq1CntMin"));
        txt_maq1CntMin->setGeometry(QRect(20, 160, 121, 31));
        txt_maq1CntProdTiempo = new QLineEdit(groupBox_3);
        txt_maq1CntProdTiempo->setObjectName(QString::fromUtf8("txt_maq1CntProdTiempo"));
        txt_maq1CntProdTiempo->setGeometry(QRect(220, 70, 121, 31));
        txt_maq1CntMax = new QLineEdit(groupBox_3);
        txt_maq1CntMax->setObjectName(QString::fromUtf8("txt_maq1CntMax"));
        txt_maq1CntMax->setGeometry(QRect(220, 160, 121, 31));
        label_12 = new QLabel(groupBox_3);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(220, 120, 121, 31));
        groupBox_4 = new QGroupBox(centralwidget);
        groupBox_4->setObjectName(QString::fromUtf8("groupBox_4"));
        groupBox_4->setGeometry(QRect(360, 270, 371, 251));
        groupBox_4->setFont(font1);
        groupBox_4->setAlignment(Qt::AlignCenter);
        label_13 = new QLabel(groupBox_4);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(10, 30, 141, 31));
        txt_maq2TmpProd = new QLineEdit(groupBox_4);
        txt_maq2TmpProd->setObjectName(QString::fromUtf8("txt_maq2TmpProd"));
        txt_maq2TmpProd->setGeometry(QRect(20, 70, 121, 31));
        label_14 = new QLabel(groupBox_4);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(210, 30, 141, 31));
        btn_maq2Ins = new QPushButton(groupBox_4);
        btn_maq2Ins->setObjectName(QString::fromUtf8("btn_maq2Ins"));
        btn_maq2Ins->setGeometry(QRect(140, 200, 80, 31));
        txt_maq2CntMin = new QLineEdit(groupBox_4);
        txt_maq2CntMin->setObjectName(QString::fromUtf8("txt_maq2CntMin"));
        txt_maq2CntMin->setGeometry(QRect(20, 160, 121, 31));
        txt_maq2CntProdTiempo = new QLineEdit(groupBox_4);
        txt_maq2CntProdTiempo->setObjectName(QString::fromUtf8("txt_maq2CntProdTiempo"));
        txt_maq2CntProdTiempo->setGeometry(QRect(220, 70, 121, 31));
        txt_maq2CntMax = new QLineEdit(groupBox_4);
        txt_maq2CntMax->setObjectName(QString::fromUtf8("txt_maq2CntMax"));
        txt_maq2CntMax->setGeometry(QRect(220, 160, 121, 31));
        label_16 = new QLabel(groupBox_4);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setGeometry(QRect(220, 120, 121, 31));
        label_23 = new QLabel(groupBox_4);
        label_23->setObjectName(QString::fromUtf8("label_23"));
        label_23->setGeometry(QRect(20, 120, 121, 31));
        groupBox_5 = new QGroupBox(centralwidget);
        groupBox_5->setObjectName(QString::fromUtf8("groupBox_5"));
        groupBox_5->setGeometry(QRect(360, 530, 371, 251));
        groupBox_5->setFont(font1);
        groupBox_5->setAlignment(Qt::AlignCenter);
        label_17 = new QLabel(groupBox_5);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setGeometry(QRect(10, 30, 141, 31));
        txt_maqChTmpProd = new QLineEdit(groupBox_5);
        txt_maqChTmpProd->setObjectName(QString::fromUtf8("txt_maqChTmpProd"));
        txt_maqChTmpProd->setGeometry(QRect(20, 70, 121, 31));
        label_18 = new QLabel(groupBox_5);
        label_18->setObjectName(QString::fromUtf8("label_18"));
        label_18->setGeometry(QRect(210, 30, 141, 31));
        btn_maqChIns = new QPushButton(groupBox_5);
        btn_maqChIns->setObjectName(QString::fromUtf8("btn_maqChIns"));
        btn_maqChIns->setGeometry(QRect(140, 210, 80, 31));
        label_19 = new QLabel(groupBox_5);
        label_19->setObjectName(QString::fromUtf8("label_19"));
        label_19->setGeometry(QRect(20, 120, 121, 31));
        txt_maqChCntMin = new QLineEdit(groupBox_5);
        txt_maqChCntMin->setObjectName(QString::fromUtf8("txt_maqChCntMin"));
        txt_maqChCntMin->setGeometry(QRect(20, 160, 121, 31));
        txt_maqChCntProdTiempo = new QLineEdit(groupBox_5);
        txt_maqChCntProdTiempo->setObjectName(QString::fromUtf8("txt_maqChCntProdTiempo"));
        txt_maqChCntProdTiempo->setGeometry(QRect(220, 70, 121, 31));
        txt_maqChCntMax = new QLineEdit(groupBox_5);
        txt_maqChCntMax->setObjectName(QString::fromUtf8("txt_maqChCntMax"));
        txt_maqChCntMax->setGeometry(QRect(220, 160, 121, 31));
        label_20 = new QLabel(groupBox_5);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setGeometry(QRect(220, 120, 121, 31));
        groupBox_6 = new QGroupBox(centralwidget);
        groupBox_6->setObjectName(QString::fromUtf8("groupBox_6"));
        groupBox_6->setGeometry(QRect(750, 0, 371, 131));
        groupBox_6->setFont(font1);
        groupBox_6->setAlignment(Qt::AlignCenter);
        label_21 = new QLabel(groupBox_6);
        label_21->setObjectName(QString::fromUtf8("label_21"));
        label_21->setGeometry(QRect(50, 30, 51, 31));
        txt_BTMMax = new QLineEdit(groupBox_6);
        txt_BTMMax->setObjectName(QString::fromUtf8("txt_BTMMax"));
        txt_BTMMax->setGeometry(QRect(20, 70, 121, 31));
        btn_BTMIns = new QPushButton(groupBox_6);
        btn_BTMIns->setObjectName(QString::fromUtf8("btn_BTMIns"));
        btn_BTMIns->setGeometry(QRect(209, 70, 101, 31));
        groupBox_7 = new QGroupBox(centralwidget);
        groupBox_7->setObjectName(QString::fromUtf8("groupBox_7"));
        groupBox_7->setGeometry(QRect(750, 130, 371, 121));
        groupBox_7->setFont(font1);
        groupBox_7->setAlignment(Qt::AlignCenter);
        label_22 = new QLabel(groupBox_7);
        label_22->setObjectName(QString::fromUtf8("label_22"));
        label_22->setGeometry(QRect(50, 30, 51, 31));
        txt_BTChMax = new QLineEdit(groupBox_7);
        txt_BTChMax->setObjectName(QString::fromUtf8("txt_BTChMax"));
        txt_BTChMax->setGeometry(QRect(20, 70, 121, 31));
        btn_BTChIns = new QPushButton(groupBox_7);
        btn_BTChIns->setObjectName(QString::fromUtf8("btn_BTChIns"));
        btn_BTChIns->setGeometry(QRect(209, 70, 101, 31));
        groupBox_8 = new QGroupBox(centralwidget);
        groupBox_8->setObjectName(QString::fromUtf8("groupBox_8"));
        groupBox_8->setGeometry(QRect(750, 250, 371, 141));
        groupBox_8->setFont(font1);
        groupBox_8->setAlignment(Qt::AlignCenter);
        label_24 = new QLabel(groupBox_8);
        label_24->setObjectName(QString::fromUtf8("label_24"));
        label_24->setGeometry(QRect(10, 30, 141, 31));
        txt_maqEmsTmpProd = new QLineEdit(groupBox_8);
        txt_maqEmsTmpProd->setObjectName(QString::fromUtf8("txt_maqEmsTmpProd"));
        txt_maqEmsTmpProd->setGeometry(QRect(20, 70, 121, 31));
        label_25 = new QLabel(groupBox_8);
        label_25->setObjectName(QString::fromUtf8("label_25"));
        label_25->setGeometry(QRect(200, 30, 141, 31));
        btn_maqEmsIns = new QPushButton(groupBox_8);
        btn_maqEmsIns->setObjectName(QString::fromUtf8("btn_maqEmsIns"));
        btn_maqEmsIns->setGeometry(QRect(140, 110, 80, 31));
        txt_maqEmsCntProdXTiemp = new QLineEdit(groupBox_8);
        txt_maqEmsCntProdXTiemp->setObjectName(QString::fromUtf8("txt_maqEmsCntProdXTiemp"));
        txt_maqEmsCntProdXTiemp->setGeometry(QRect(210, 70, 121, 31));
        groupBox_9 = new QGroupBox(centralwidget);
        groupBox_9->setObjectName(QString::fromUtf8("groupBox_9"));
        groupBox_9->setGeometry(QRect(750, 390, 371, 121));
        groupBox_9->setFont(font1);
        groupBox_9->setAlignment(Qt::AlignCenter);
        label_26 = new QLabel(groupBox_9);
        label_26->setObjectName(QString::fromUtf8("label_26"));
        label_26->setGeometry(QRect(50, 30, 51, 31));
        txt_BTEmsHorMax = new QLineEdit(groupBox_9);
        txt_BTEmsHorMax->setObjectName(QString::fromUtf8("txt_BTEmsHorMax"));
        txt_BTEmsHorMax->setGeometry(QRect(20, 70, 121, 31));
        btn_BTEmsHorIns = new QPushButton(groupBox_9);
        btn_BTEmsHorIns->setObjectName(QString::fromUtf8("btn_BTEmsHorIns"));
        btn_BTEmsHorIns->setGeometry(QRect(209, 70, 101, 31));
        groupBox_10 = new QGroupBox(centralwidget);
        groupBox_10->setObjectName(QString::fromUtf8("groupBox_10"));
        groupBox_10->setGeometry(QRect(1140, 0, 371, 451));
        groupBox_10->setFont(font1);
        groupBox_10->setAlignment(Qt::AlignCenter);
        label_27 = new QLabel(groupBox_10);
        label_27->setObjectName(QString::fromUtf8("label_27"));
        label_27->setGeometry(QRect(40, 30, 131, 16));
        txt_HorTmpHorneado = new QLineEdit(groupBox_10);
        txt_HorTmpHorneado->setObjectName(QString::fromUtf8("txt_HorTmpHorneado"));
        txt_HorTmpHorneado->setGeometry(QRect(50, 50, 121, 31));
        btn_HorIns = new QPushButton(groupBox_10);
        btn_HorIns->setObjectName(QString::fromUtf8("btn_HorIns"));
        btn_HorIns->setGeometry(QRect(240, 50, 80, 24));
        groupBox_11 = new QGroupBox(groupBox_10);
        groupBox_11->setObjectName(QString::fromUtf8("groupBox_11"));
        groupBox_11->setGeometry(QRect(20, 90, 161, 121));
        QFont font2;
        font2.setPointSize(11);
        font2.setItalic(false);
        groupBox_11->setFont(font2);
        groupBox_11->setAlignment(Qt::AlignCenter);
        txt_bnd1Cap = new QLineEdit(groupBox_11);
        txt_bnd1Cap->setObjectName(QString::fromUtf8("txt_bnd1Cap"));
        txt_bnd1Cap->setGeometry(QRect(10, 30, 71, 41));
        rBtn_bnd1On = new QRadioButton(groupBox_11);
        rBtn_bnd1On->setObjectName(QString::fromUtf8("rBtn_bnd1On"));
        rBtn_bnd1On->setGeometry(QRect(100, 40, 51, 22));
        btn_bnd1Ins = new QPushButton(groupBox_11);
        btn_bnd1Ins->setObjectName(QString::fromUtf8("btn_bnd1Ins"));
        btn_bnd1Ins->setGeometry(QRect(50, 80, 61, 31));
        groupBox_12 = new QGroupBox(groupBox_10);
        groupBox_12->setObjectName(QString::fromUtf8("groupBox_12"));
        groupBox_12->setGeometry(QRect(200, 90, 161, 121));
        groupBox_12->setFont(font2);
        groupBox_12->setAlignment(Qt::AlignCenter);
        txt_bnd2Cap = new QLineEdit(groupBox_12);
        txt_bnd2Cap->setObjectName(QString::fromUtf8("txt_bnd2Cap"));
        txt_bnd2Cap->setGeometry(QRect(10, 30, 71, 41));
        rBtn_bnd2On = new QRadioButton(groupBox_12);
        rBtn_bnd2On->setObjectName(QString::fromUtf8("rBtn_bnd2On"));
        rBtn_bnd2On->setGeometry(QRect(100, 40, 51, 22));
        btn_bnd2Ins = new QPushButton(groupBox_12);
        btn_bnd2Ins->setObjectName(QString::fromUtf8("btn_bnd2Ins"));
        btn_bnd2Ins->setGeometry(QRect(50, 80, 61, 31));
        groupBox_13 = new QGroupBox(groupBox_10);
        groupBox_13->setObjectName(QString::fromUtf8("groupBox_13"));
        groupBox_13->setGeometry(QRect(20, 210, 161, 121));
        groupBox_13->setFont(font2);
        groupBox_13->setAlignment(Qt::AlignCenter);
        txt_bnd3Cap = new QLineEdit(groupBox_13);
        txt_bnd3Cap->setObjectName(QString::fromUtf8("txt_bnd3Cap"));
        txt_bnd3Cap->setGeometry(QRect(10, 30, 71, 41));
        rBtn_bnd3On = new QRadioButton(groupBox_13);
        rBtn_bnd3On->setObjectName(QString::fromUtf8("rBtn_bnd3On"));
        rBtn_bnd3On->setGeometry(QRect(100, 20, 51, 22));
        btn_bnd3Ins = new QPushButton(groupBox_13);
        btn_bnd3Ins->setObjectName(QString::fromUtf8("btn_bnd3Ins"));
        btn_bnd3Ins->setGeometry(QRect(50, 80, 61, 31));
        rBtn_bnd3Off = new QRadioButton(groupBox_13);
        rBtn_bnd3Off->setObjectName(QString::fromUtf8("rBtn_bnd3Off"));
        rBtn_bnd3Off->setGeometry(QRect(100, 50, 51, 22));
        groupBox_14 = new QGroupBox(groupBox_10);
        groupBox_14->setObjectName(QString::fromUtf8("groupBox_14"));
        groupBox_14->setGeometry(QRect(200, 210, 161, 121));
        groupBox_14->setFont(font2);
        groupBox_14->setAlignment(Qt::AlignCenter);
        txt_bnd4Cap = new QLineEdit(groupBox_14);
        txt_bnd4Cap->setObjectName(QString::fromUtf8("txt_bnd4Cap"));
        txt_bnd4Cap->setGeometry(QRect(10, 30, 71, 41));
        rBtn_bnd4On = new QRadioButton(groupBox_14);
        rBtn_bnd4On->setObjectName(QString::fromUtf8("rBtn_bnd4On"));
        rBtn_bnd4On->setGeometry(QRect(100, 20, 51, 22));
        btn_bnd4Ins = new QPushButton(groupBox_14);
        btn_bnd4Ins->setObjectName(QString::fromUtf8("btn_bnd4Ins"));
        btn_bnd4Ins->setGeometry(QRect(50, 80, 61, 31));
        rBtn_bnd4Off = new QRadioButton(groupBox_14);
        rBtn_bnd4Off->setObjectName(QString::fromUtf8("rBtn_bnd4Off"));
        rBtn_bnd4Off->setGeometry(QRect(100, 50, 99, 22));
        groupBox_15 = new QGroupBox(groupBox_10);
        groupBox_15->setObjectName(QString::fromUtf8("groupBox_15"));
        groupBox_15->setGeometry(QRect(20, 330, 161, 121));
        groupBox_15->setFont(font2);
        groupBox_15->setAlignment(Qt::AlignCenter);
        txt_bnd5Cap = new QLineEdit(groupBox_15);
        txt_bnd5Cap->setObjectName(QString::fromUtf8("txt_bnd5Cap"));
        txt_bnd5Cap->setGeometry(QRect(10, 30, 71, 41));
        rBtn_bnd5On = new QRadioButton(groupBox_15);
        rBtn_bnd5On->setObjectName(QString::fromUtf8("rBtn_bnd5On"));
        rBtn_bnd5On->setGeometry(QRect(100, 20, 51, 22));
        btn_bnd5Ins = new QPushButton(groupBox_15);
        btn_bnd5Ins->setObjectName(QString::fromUtf8("btn_bnd5Ins"));
        btn_bnd5Ins->setGeometry(QRect(50, 80, 61, 31));
        rBtn_bnd5Off = new QRadioButton(groupBox_15);
        rBtn_bnd5Off->setObjectName(QString::fromUtf8("rBtn_bnd5Off"));
        rBtn_bnd5Off->setGeometry(QRect(100, 50, 51, 22));
        groupBox_16 = new QGroupBox(groupBox_10);
        groupBox_16->setObjectName(QString::fromUtf8("groupBox_16"));
        groupBox_16->setGeometry(QRect(200, 330, 161, 121));
        groupBox_16->setFont(font2);
        groupBox_16->setAlignment(Qt::AlignCenter);
        txt_bnd6Cap = new QLineEdit(groupBox_16);
        txt_bnd6Cap->setObjectName(QString::fromUtf8("txt_bnd6Cap"));
        txt_bnd6Cap->setGeometry(QRect(10, 30, 71, 41));
        rBtn_bnd6On = new QRadioButton(groupBox_16);
        rBtn_bnd6On->setObjectName(QString::fromUtf8("rBtn_bnd6On"));
        rBtn_bnd6On->setGeometry(QRect(100, 20, 51, 22));
        btn_bnd6Ins = new QPushButton(groupBox_16);
        btn_bnd6Ins->setObjectName(QString::fromUtf8("btn_bnd6Ins"));
        btn_bnd6Ins->setGeometry(QRect(50, 80, 61, 31));
        rBtn_bnd6Off = new QRadioButton(groupBox_16);
        rBtn_bnd6Off->setObjectName(QString::fromUtf8("rBtn_bnd6Off"));
        rBtn_bnd6Off->setGeometry(QRect(100, 50, 51, 22));
        groupBox_17 = new QGroupBox(centralwidget);
        groupBox_17->setObjectName(QString::fromUtf8("groupBox_17"));
        groupBox_17->setGeometry(QRect(750, 520, 371, 121));
        groupBox_17->setFont(font1);
        groupBox_17->setAlignment(Qt::AlignCenter);
        label_28 = new QLabel(groupBox_17);
        label_28->setObjectName(QString::fromUtf8("label_28"));
        label_28->setGeometry(QRect(50, 30, 51, 31));
        txt_BTHorSupMax = new QLineEdit(groupBox_17);
        txt_BTHorSupMax->setObjectName(QString::fromUtf8("txt_BTHorSupMax"));
        txt_BTHorSupMax->setGeometry(QRect(20, 70, 121, 31));
        btn_BTHorSupIns = new QPushButton(groupBox_17);
        btn_BTHorSupIns->setObjectName(QString::fromUtf8("btn_BTHorSupIns"));
        btn_BTHorSupIns->setGeometry(QRect(209, 70, 101, 31));
        groupBox_18 = new QGroupBox(centralwidget);
        groupBox_18->setObjectName(QString::fromUtf8("groupBox_18"));
        groupBox_18->setGeometry(QRect(750, 650, 371, 131));
        groupBox_18->setFont(font1);
        groupBox_18->setAlignment(Qt::AlignCenter);
        label_29 = new QLabel(groupBox_18);
        label_29->setObjectName(QString::fromUtf8("label_29"));
        label_29->setGeometry(QRect(20, 30, 81, 31));
        txt_Sup1Prob = new QLineEdit(groupBox_18);
        txt_Sup1Prob->setObjectName(QString::fromUtf8("txt_Sup1Prob"));
        txt_Sup1Prob->setGeometry(QRect(20, 70, 81, 31));
        btn_SupIns = new QPushButton(groupBox_18);
        btn_SupIns->setObjectName(QString::fromUtf8("btn_SupIns"));
        btn_SupIns->setGeometry(QRect(150, 90, 80, 31));
        txt_Sup2Prob = new QLineEdit(groupBox_18);
        txt_Sup2Prob->setObjectName(QString::fromUtf8("txt_Sup2Prob"));
        txt_Sup2Prob->setGeometry(QRect(270, 70, 81, 31));
        label_30 = new QLabel(groupBox_18);
        label_30->setObjectName(QString::fromUtf8("label_30"));
        label_30->setGeometry(QRect(270, 30, 81, 31));
        groupBox_22 = new QGroupBox(centralwidget);
        groupBox_22->setObjectName(QString::fromUtf8("groupBox_22"));
        groupBox_22->setGeometry(QRect(1140, 490, 371, 131));
        groupBox_22->setFont(font1);
        groupBox_22->setAlignment(Qt::AlignCenter);
        btn_maqEmpIns = new QPushButton(groupBox_22);
        btn_maqEmpIns->setObjectName(QString::fromUtf8("btn_maqEmpIns"));
        btn_maqEmpIns->setGeometry(QRect(150, 90, 81, 31));
        txt_maqEmpCap = new QLineEdit(groupBox_22);
        txt_maqEmpCap->setObjectName(QString::fromUtf8("txt_maqEmpCap"));
        txt_maqEmpCap->setGeometry(QRect(270, 60, 81, 21));
        txt_maqEmpTmp = new QLineEdit(groupBox_22);
        txt_maqEmpTmp->setObjectName(QString::fromUtf8("txt_maqEmpTmp"));
        txt_maqEmpTmp->setGeometry(QRect(20, 60, 81, 21));
        label_40 = new QLabel(groupBox_22);
        label_40->setObjectName(QString::fromUtf8("label_40"));
        label_40->setGeometry(QRect(30, 30, 51, 20));
        txt_transCap_3 = new QLabel(groupBox_22);
        txt_transCap_3->setObjectName(QString::fromUtf8("txt_transCap_3"));
        txt_transCap_3->setGeometry(QRect(280, 30, 51, 20));
        groupBox_23 = new QGroupBox(centralwidget);
        groupBox_23->setObjectName(QString::fromUtf8("groupBox_23"));
        groupBox_23->setGeometry(QRect(1140, 650, 371, 131));
        groupBox_23->setFont(font1);
        groupBox_23->setAlignment(Qt::AlignCenter);
        label_39 = new QLabel(groupBox_23);
        label_39->setObjectName(QString::fromUtf8("label_39"));
        label_39->setGeometry(QRect(30, 40, 51, 20));
        txt_transCap_2 = new QLineEdit(groupBox_23);
        txt_transCap_2->setObjectName(QString::fromUtf8("txt_transCap_2"));
        txt_transCap_2->setGeometry(QRect(270, 70, 81, 31));
        txt_transCap = new QLabel(groupBox_23);
        txt_transCap->setObjectName(QString::fromUtf8("txt_transCap"));
        txt_transCap->setGeometry(QRect(280, 40, 51, 20));
        txt_transTmp = new QLineEdit(groupBox_23);
        txt_transTmp->setObjectName(QString::fromUtf8("txt_transTmp"));
        txt_transTmp->setGeometry(QRect(20, 70, 81, 31));
        btn_transIns = new QPushButton(groupBox_23);
        btn_transIns->setObjectName(QString::fromUtf8("btn_transIns"));
        btn_transIns->setGeometry(QRect(150, 90, 81, 31));
        VentanaConfigurar->setCentralWidget(centralwidget);
        menubar = new QMenuBar(VentanaConfigurar);
        menubar->setObjectName(QString::fromUtf8("menubar"));
        menubar->setGeometry(QRect(0, 0, 1524, 21));
        VentanaConfigurar->setMenuBar(menubar);
        statusbar = new QStatusBar(VentanaConfigurar);
        statusbar->setObjectName(QString::fromUtf8("statusbar"));
        VentanaConfigurar->setStatusBar(statusbar);

        retranslateUi(VentanaConfigurar);

        QMetaObject::connectSlotsByName(VentanaConfigurar);
    } // setupUi

    void retranslateUi(QMainWindow *VentanaConfigurar)
    {
        VentanaConfigurar->setWindowTitle(QCoreApplication::translate("VentanaConfigurar", "Ventana de Configuraci\303\263n", nullptr));
        insertarPaquete->setTitle(QCoreApplication::translate("VentanaConfigurar", "Insertar Paquete", nullptr));
        txt_InsNom->setText(QString());
        label->setText(QCoreApplication::translate("VentanaConfigurar", "Nombre del paquete:", nullptr));
        label_2->setText(QCoreApplication::translate("VentanaConfigurar", "Cantidad de galletas: ", nullptr));
        txt_InsCntGalletas->setText(QCoreApplication::translate("VentanaConfigurar", "0", nullptr));
        label_3->setText(QCoreApplication::translate("VentanaConfigurar", "Cantidad de paquetes: ", nullptr));
        txt_InsCntPaq->setText(QCoreApplication::translate("VentanaConfigurar", "0", nullptr));
        btn_InsIns->setText(QCoreApplication::translate("VentanaConfigurar", "Insertar", nullptr));
        groupBox->setTitle(QCoreApplication::translate("VentanaConfigurar", "Receta", nullptr));
        label_4->setText(QCoreApplication::translate("VentanaConfigurar", "Cantidad de masa por galleta: ", nullptr));
        txt_RecCntMasaGall->setText(QCoreApplication::translate("VentanaConfigurar", "0", nullptr));
        label_5->setText(QCoreApplication::translate("VentanaConfigurar", "Cantidad de chocolate por galleta: ", nullptr));
        txt_RecCntChocoGall->setText(QCoreApplication::translate("VentanaConfigurar", "0", nullptr));
        btn_RecIns->setText(QCoreApplication::translate("VentanaConfigurar", "Insertar", nullptr));
        groupBox_2->setTitle(QCoreApplication::translate("VentanaConfigurar", "Carrito", nullptr));
        label_6->setText(QCoreApplication::translate("VentanaConfigurar", "Tiempo de viaje por env\303\255o:", nullptr));
        txt_CarTmpXEnv->setText(QCoreApplication::translate("VentanaConfigurar", "0", nullptr));
        label_7->setText(QCoreApplication::translate("VentanaConfigurar", "Capacidad de transporte de chocolate:", nullptr));
        txt_CarTransChoco->setText(QCoreApplication::translate("VentanaConfigurar", "0", nullptr));
        btn_CarIns->setText(QCoreApplication::translate("VentanaConfigurar", "Insertar", nullptr));
        label_8->setText(QCoreApplication::translate("VentanaConfigurar", "Capacidad de transporte de masa:", nullptr));
        txt_CarTransMasa->setText(QCoreApplication::translate("VentanaConfigurar", "0", nullptr));
        groupBox_3->setTitle(QCoreApplication::translate("VentanaConfigurar", "M\303\241quina de Masa 1", nullptr));
        label_9->setText(QCoreApplication::translate("VentanaConfigurar", "Tiempo de producci\303\263n:", nullptr));
        txt_maq1TmpProd->setText(QCoreApplication::translate("VentanaConfigurar", "0", nullptr));
        label_10->setText(QCoreApplication::translate("VentanaConfigurar", "Producci\303\263n por tiempo:", nullptr));
        btn_maq1Ins->setText(QCoreApplication::translate("VentanaConfigurar", "Insertar", nullptr));
        label_11->setText(QCoreApplication::translate("VentanaConfigurar", " Cantidad m\303\255nima:", nullptr));
        txt_maq1CntMin->setText(QCoreApplication::translate("VentanaConfigurar", "0", nullptr));
        txt_maq1CntProdTiempo->setText(QCoreApplication::translate("VentanaConfigurar", "0", nullptr));
        txt_maq1CntMax->setText(QCoreApplication::translate("VentanaConfigurar", "0", nullptr));
        label_12->setText(QCoreApplication::translate("VentanaConfigurar", "  Cantidad m\303\241xima:", nullptr));
        groupBox_4->setTitle(QCoreApplication::translate("VentanaConfigurar", "M\303\241quina de Masa 2", nullptr));
        label_13->setText(QCoreApplication::translate("VentanaConfigurar", "Tiempo de producci\303\263n:", nullptr));
        txt_maq2TmpProd->setText(QCoreApplication::translate("VentanaConfigurar", "0", nullptr));
        label_14->setText(QCoreApplication::translate("VentanaConfigurar", "Producci\303\263n por tiempo:", nullptr));
        btn_maq2Ins->setText(QCoreApplication::translate("VentanaConfigurar", "Insertar", nullptr));
        txt_maq2CntMin->setText(QCoreApplication::translate("VentanaConfigurar", "0", nullptr));
        txt_maq2CntProdTiempo->setText(QCoreApplication::translate("VentanaConfigurar", "0", nullptr));
        txt_maq2CntMax->setText(QCoreApplication::translate("VentanaConfigurar", "0", nullptr));
        label_16->setText(QCoreApplication::translate("VentanaConfigurar", "  Cantidad m\303\241xima:", nullptr));
        label_23->setText(QCoreApplication::translate("VentanaConfigurar", "  Cantidad m\303\255nima:", nullptr));
        groupBox_5->setTitle(QCoreApplication::translate("VentanaConfigurar", "M\303\241quina de Chocolate", nullptr));
        label_17->setText(QCoreApplication::translate("VentanaConfigurar", "Tiempo de producci\303\263n:", nullptr));
        txt_maqChTmpProd->setText(QCoreApplication::translate("VentanaConfigurar", "0", nullptr));
        label_18->setText(QCoreApplication::translate("VentanaConfigurar", "Producci\303\263n por tiempo:", nullptr));
        btn_maqChIns->setText(QCoreApplication::translate("VentanaConfigurar", "Insertar", nullptr));
        label_19->setText(QCoreApplication::translate("VentanaConfigurar", "  Cantidad m\303\255nima:", nullptr));
        txt_maqChCntMin->setText(QCoreApplication::translate("VentanaConfigurar", "0", nullptr));
        txt_maqChCntProdTiempo->setText(QCoreApplication::translate("VentanaConfigurar", "0", nullptr));
        txt_maqChCntMax->setText(QCoreApplication::translate("VentanaConfigurar", "0", nullptr));
        label_20->setText(QCoreApplication::translate("VentanaConfigurar", " Cantidad m\303\241xima:", nullptr));
        groupBox_6->setTitle(QCoreApplication::translate("VentanaConfigurar", "Banda Transportadora de Masa", nullptr));
        label_21->setText(QCoreApplication::translate("VentanaConfigurar", "M\303\241ximo:", nullptr));
        txt_BTMMax->setText(QCoreApplication::translate("VentanaConfigurar", "0", nullptr));
        btn_BTMIns->setText(QCoreApplication::translate("VentanaConfigurar", "Insertar", nullptr));
        groupBox_7->setTitle(QCoreApplication::translate("VentanaConfigurar", "Banda Transportadora de Chocolate", nullptr));
        label_22->setText(QCoreApplication::translate("VentanaConfigurar", "M\303\241ximo:", nullptr));
        txt_BTChMax->setText(QCoreApplication::translate("VentanaConfigurar", "0", nullptr));
        btn_BTChIns->setText(QCoreApplication::translate("VentanaConfigurar", "Insertar", nullptr));
        groupBox_8->setTitle(QCoreApplication::translate("VentanaConfigurar", "M\303\241quina Ensambladora", nullptr));
        label_24->setText(QCoreApplication::translate("VentanaConfigurar", "Tiempo de producci\303\263n:", nullptr));
        txt_maqEmsTmpProd->setText(QCoreApplication::translate("VentanaConfigurar", "0", nullptr));
        label_25->setText(QCoreApplication::translate("VentanaConfigurar", "Producci\303\263n por tiempo:", nullptr));
        btn_maqEmsIns->setText(QCoreApplication::translate("VentanaConfigurar", "Insertar", nullptr));
        txt_maqEmsCntProdXTiemp->setText(QCoreApplication::translate("VentanaConfigurar", "0", nullptr));
        groupBox_9->setTitle(QCoreApplication::translate("VentanaConfigurar", "Banda Transportadora de galletas por hornear", nullptr));
        label_26->setText(QCoreApplication::translate("VentanaConfigurar", "M\303\241ximo:", nullptr));
        txt_BTEmsHorMax->setText(QCoreApplication::translate("VentanaConfigurar", "0", nullptr));
        btn_BTEmsHorIns->setText(QCoreApplication::translate("VentanaConfigurar", "Insertar", nullptr));
        groupBox_10->setTitle(QCoreApplication::translate("VentanaConfigurar", "Horno", nullptr));
        label_27->setText(QCoreApplication::translate("VentanaConfigurar", "Tiempo de horneado: ", nullptr));
        txt_HorTmpHorneado->setText(QCoreApplication::translate("VentanaConfigurar", "0", nullptr));
        btn_HorIns->setText(QCoreApplication::translate("VentanaConfigurar", "Insertar", nullptr));
        groupBox_11->setTitle(QCoreApplication::translate("VentanaConfigurar", "Bandeja 1", nullptr));
        txt_bnd1Cap->setText(QCoreApplication::translate("VentanaConfigurar", " Capacidad", nullptr));
        rBtn_bnd1On->setText(QCoreApplication::translate("VentanaConfigurar", "ON", nullptr));
        btn_bnd1Ins->setText(QCoreApplication::translate("VentanaConfigurar", "\342\210\232", nullptr));
        groupBox_12->setTitle(QCoreApplication::translate("VentanaConfigurar", "Bandeja 2", nullptr));
        txt_bnd2Cap->setText(QCoreApplication::translate("VentanaConfigurar", " Capacidad", nullptr));
        rBtn_bnd2On->setText(QCoreApplication::translate("VentanaConfigurar", "ON", nullptr));
        btn_bnd2Ins->setText(QCoreApplication::translate("VentanaConfigurar", "\342\210\232", nullptr));
        groupBox_13->setTitle(QCoreApplication::translate("VentanaConfigurar", "Bandeja 3", nullptr));
        txt_bnd3Cap->setText(QCoreApplication::translate("VentanaConfigurar", " Capacidad", nullptr));
        rBtn_bnd3On->setText(QCoreApplication::translate("VentanaConfigurar", "ON", nullptr));
        btn_bnd3Ins->setText(QCoreApplication::translate("VentanaConfigurar", "\342\210\232", nullptr));
        rBtn_bnd3Off->setText(QCoreApplication::translate("VentanaConfigurar", "OFF", nullptr));
        groupBox_14->setTitle(QCoreApplication::translate("VentanaConfigurar", "Bandeja 4", nullptr));
        txt_bnd4Cap->setText(QCoreApplication::translate("VentanaConfigurar", " Capacidad", nullptr));
        rBtn_bnd4On->setText(QCoreApplication::translate("VentanaConfigurar", "ON", nullptr));
        btn_bnd4Ins->setText(QCoreApplication::translate("VentanaConfigurar", "\342\210\232", nullptr));
        rBtn_bnd4Off->setText(QCoreApplication::translate("VentanaConfigurar", "OFF", nullptr));
        groupBox_15->setTitle(QCoreApplication::translate("VentanaConfigurar", "Bandeja 5", nullptr));
        txt_bnd5Cap->setText(QCoreApplication::translate("VentanaConfigurar", " Capacidad", nullptr));
        rBtn_bnd5On->setText(QCoreApplication::translate("VentanaConfigurar", "ON", nullptr));
        btn_bnd5Ins->setText(QCoreApplication::translate("VentanaConfigurar", "\342\210\232", nullptr));
        rBtn_bnd5Off->setText(QCoreApplication::translate("VentanaConfigurar", "OFF", nullptr));
        groupBox_16->setTitle(QCoreApplication::translate("VentanaConfigurar", "Bandeja 6", nullptr));
        txt_bnd6Cap->setText(QCoreApplication::translate("VentanaConfigurar", " Capacidad", nullptr));
        rBtn_bnd6On->setText(QCoreApplication::translate("VentanaConfigurar", "ON", nullptr));
        btn_bnd6Ins->setText(QCoreApplication::translate("VentanaConfigurar", "\342\210\232", nullptr));
        rBtn_bnd6Off->setText(QCoreApplication::translate("VentanaConfigurar", "OFF", nullptr));
        groupBox_17->setTitle(QCoreApplication::translate("VentanaConfigurar", "Banda Transportadora de galletas horneadas a supervisar", nullptr));
        label_28->setText(QCoreApplication::translate("VentanaConfigurar", "M\303\241ximo:", nullptr));
        txt_BTHorSupMax->setText(QCoreApplication::translate("VentanaConfigurar", "0", nullptr));
        btn_BTHorSupIns->setText(QCoreApplication::translate("VentanaConfigurar", "Insertar", nullptr));
        groupBox_18->setTitle(QCoreApplication::translate("VentanaConfigurar", "Probabilidad de los supervisores", nullptr));
        label_29->setText(QCoreApplication::translate("VentanaConfigurar", "Supervisor 1", nullptr));
        txt_Sup1Prob->setText(QCoreApplication::translate("VentanaConfigurar", "0", nullptr));
        btn_SupIns->setText(QCoreApplication::translate("VentanaConfigurar", "Insertar", nullptr));
        txt_Sup2Prob->setText(QCoreApplication::translate("VentanaConfigurar", "0", nullptr));
        label_30->setText(QCoreApplication::translate("VentanaConfigurar", "Supervisor 2", nullptr));
        groupBox_22->setTitle(QCoreApplication::translate("VentanaConfigurar", "M\303\241quina Empacadora", nullptr));
        btn_maqEmpIns->setText(QCoreApplication::translate("VentanaConfigurar", "Insertar", nullptr));
        txt_maqEmpCap->setText(QCoreApplication::translate("VentanaConfigurar", "0", nullptr));
        txt_maqEmpTmp->setText(QCoreApplication::translate("VentanaConfigurar", "0", nullptr));
        label_40->setText(QCoreApplication::translate("VentanaConfigurar", "Tiempo:", nullptr));
        txt_transCap_3->setText(QCoreApplication::translate("VentanaConfigurar", "M\303\241ximo:", nullptr));
        groupBox_23->setTitle(QCoreApplication::translate("VentanaConfigurar", "Transportadores", nullptr));
        label_39->setText(QCoreApplication::translate("VentanaConfigurar", "Tiempo:", nullptr));
        txt_transCap_2->setText(QCoreApplication::translate("VentanaConfigurar", "0", nullptr));
        txt_transCap->setText(QCoreApplication::translate("VentanaConfigurar", "M\303\241ximo:", nullptr));
        txt_transTmp->setText(QCoreApplication::translate("VentanaConfigurar", "0", nullptr));
        btn_transIns->setText(QCoreApplication::translate("VentanaConfigurar", "Insertar", nullptr));
    } // retranslateUi

};

namespace Ui {
    class VentanaConfigurar: public Ui_VentanaConfigurar {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_VENTANACONFIGURAR_H
