/********************************************************************************
** Form generated from reading UI file 'ventanaprincipal.ui'
**
** Created by: Qt User Interface Compiler version 6.1.3
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_VENTANAPRINCIPAL_H
#define UI_VENTANAPRINCIPAL_H

#include <QtCore/QVariant>
#include <QtGui/QIcon>
#include <QtWidgets/QApplication>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTableWidget>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_VentanaPrincipal
{
public:
    QWidget *centralwidget;
    QLabel *lblCantidadGalletas;
    QPushButton *btnIniciar;
    QLabel *lblChoco;
    QLabel *lblMasa;
    QLabel *lbl_TextGalletasPlani;
    QLabel *lbl_TextMasaPlani;
    QLabel *lbl_TextChocoPlani;
    QLabel *lbl_TextPlani;
    QLabel *lbl_TextMaquinaMasa1;
    QLabel *lbl_MaquinaMasa1EnProceso;
    QLabel *lbl_MaquinaMasa1Procesada;
    QLabel *lbl_TextMaquina1Actual;
    QLabel *lbl_TextMaquina1Procesada;
    QPushButton *btnPausa;
    QPushButton *btnDetener;
    QLabel *lbl_TextMaquinaMasa2;
    QLabel *lbl_TextMaquina2Actual;
    QLabel *lbl_TextMaquina2Procesada;
    QLabel *lbl_MaquinaMasa2EnProceso;
    QLabel *lbl_MaquinaMasa2Procesada;
    QLabel *lbl_TextMaquinaChoco;
    QLabel *lbl_TextMaquinaChocoActual;
    QLabel *lbl_TextMaquinaChocoProcesada;
    QLabel *lbl_MaquinaChocoProcesada;
    QLabel *lbl_MaquinaChocoEnProceso;
    QLabel *lbl_TextBandaTMasaActual;
    QLabel *lbl_TextBandaChocoProcesada;
    QLabel *lbl_BantaTMasaMax;
    QLabel *lbl_BandaTChocoActual;
    QLabel *lbl_TextBandaMasa;
    QLabel *lbl_BandaTChocoMax;
    QLabel *lbl_BandaTMasaActual;
    QLabel *lbl_TextBandaTMasaProcesada;
    QLabel *lbl_TextBandaTChocoActual;
    QLabel *lbl_TextBandaChoco;
    QLabel *lbl_MaquinaEnsambladora;
    QLabel *lbl_TextEnsambladoraProducida;
    QLabel *lbl_EnsambladoraProducida;
    QLabel *lbl_TextBandaTransportadora;
    QLabel *lbl_TextBandaTEnsambladoraActual;
    QLabel *lbl_TextBandaTEnsambladoraMax;
    QLabel *lbl_BandaTEnsambladoraActual;
    QLabel *lbl_BandaTEnsambladoraMax;
    QLabel *lbl_Horno;
    QLabel *lbl_TextActualHorno;
    QLabel *lbl_TexthorneadasHorno;
    QLabel *lbl_actualHorno;
    QLabel *lbl_horneadasHorno;
    QLabel *lbl_Supervisores;
    QLabel *lbl_TextActualSupervisores;
    QLabel *lbl_actualSupervisores;
    QGroupBox *grupoEstadoMaquina1;
    QRadioButton *radioButtonEncenderMaquina1;
    QRadioButton *radioButtonApagarMaquina1;
    QPushButton *btnCambiarEstadoMaquina1;
    QGroupBox *grupoEstadoMaquina2;
    QRadioButton *radioButtonEncenderMaquina2;
    QRadioButton *radioButtonApagarMaquina2;
    QPushButton *btnCambiarEstadoMaquina2;
    QGroupBox *grupoEstadoMaquina3;
    QRadioButton *radioButtonEncenderMaquina3;
    QRadioButton *radioButtonApagarMaquina3;
    QPushButton *btnCambiarEstadoMaquina3;
    QPushButton *btnReanudar;
    QLabel *lbl_TextSupervisoresAceptadas;
    QLabel *lbl_TextSupervisoresRechazadas;
    QLabel *lbl_SupervisoresAceptadas;
    QLabel *lbl_SupervisoresRechazadas;
    QLabel *lbl_Carrito;
    QLabel *lblSup1;
    QLabel *lblSup2;
    QLabel *lbl_TextAceptadasSup2;
    QLabel *lbl_TextRechazadasSup2;
    QLabel *lbl_AceptadasSup2;
    QLabel *lbl_RechazadasSup2;
    QLabel *lbl_imgEmpacadora;
    QLabel *lbl_imgAlmacen1;
    QLabel *lbl_imgAlmacenFinal;
    QGroupBox *grupoHorno;
    QPushButton *btnCambiarEstadoHorno;
    QRadioButton *radioButtonEncenderHorno;
    QRadioButton *radioButtonApagarHorno;
    QGroupBox *groupBox;
    QRadioButton *radioButtonEncenderEnsambladora;
    QRadioButton *radioButtonApagarEnsambladora;
    QPushButton *btnCambiarEstadoEnsambladora;
    QLabel *lbl_TextMaxSupervisores;
    QLabel *lbl_SupervisoresMax;
    QTableWidget *tableWidget;
    QLabel *label;
    QTableWidget *tablaBandejas;
    QLabel *label_2;
    QTableWidget *tablaTransportes;
    QMenuBar *menubar;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *VentanaPrincipal)
    {
        if (VentanaPrincipal->objectName().isEmpty())
            VentanaPrincipal->setObjectName(QString::fromUtf8("VentanaPrincipal"));
        VentanaPrincipal->resize(1597, 850);
        VentanaPrincipal->setCursor(QCursor(Qt::ArrowCursor));
        QIcon icon;
        icon.addFile(QString::fromUtf8(":/Recursos/img/cookie.png"), QSize(), QIcon::Normal, QIcon::Off);
        VentanaPrincipal->setWindowIcon(icon);
        VentanaPrincipal->setAutoFillBackground(false);
        VentanaPrincipal->setStyleSheet(QString::fromUtf8("background-color: rgb(218, 136, 231)"));
        centralwidget = new QWidget(VentanaPrincipal);
        centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
        lblCantidadGalletas = new QLabel(centralwidget);
        lblCantidadGalletas->setObjectName(QString::fromUtf8("lblCantidadGalletas"));
        lblCantidadGalletas->setGeometry(QRect(250, 610, 121, 31));
        btnIniciar = new QPushButton(centralwidget);
        btnIniciar->setObjectName(QString::fromUtf8("btnIniciar"));
        btnIniciar->setGeometry(QRect(480, 730, 161, 71));
        lblChoco = new QLabel(centralwidget);
        lblChoco->setObjectName(QString::fromUtf8("lblChoco"));
        lblChoco->setGeometry(QRect(250, 730, 111, 31));
        lblMasa = new QLabel(centralwidget);
        lblMasa->setObjectName(QString::fromUtf8("lblMasa"));
        lblMasa->setGeometry(QRect(250, 670, 101, 31));
        lbl_TextGalletasPlani = new QLabel(centralwidget);
        lbl_TextGalletasPlani->setObjectName(QString::fromUtf8("lbl_TextGalletasPlani"));
        lbl_TextGalletasPlani->setGeometry(QRect(180, 600, 61, 51));
        QFont font;
        font.setBold(true);
        lbl_TextGalletasPlani->setFont(font);
        lbl_TextMasaPlani = new QLabel(centralwidget);
        lbl_TextMasaPlani->setObjectName(QString::fromUtf8("lbl_TextMasaPlani"));
        lbl_TextMasaPlani->setGeometry(QRect(180, 660, 61, 51));
        lbl_TextMasaPlani->setFont(font);
        lbl_TextChocoPlani = new QLabel(centralwidget);
        lbl_TextChocoPlani->setObjectName(QString::fromUtf8("lbl_TextChocoPlani"));
        lbl_TextChocoPlani->setGeometry(QRect(180, 720, 61, 51));
        QFont font1;
        font1.setPointSize(13);
        font1.setBold(true);
        lbl_TextChocoPlani->setFont(font1);
        lbl_TextPlani = new QLabel(centralwidget);
        lbl_TextPlani->setObjectName(QString::fromUtf8("lbl_TextPlani"));
        lbl_TextPlani->setGeometry(QRect(150, 450, 181, 131));
        QFont font2;
        font2.setPointSize(10);
        font2.setBold(true);
        font2.setItalic(true);
        lbl_TextPlani->setFont(font2);
        lbl_TextMaquinaMasa1 = new QLabel(centralwidget);
        lbl_TextMaquinaMasa1->setObjectName(QString::fromUtf8("lbl_TextMaquinaMasa1"));
        lbl_TextMaquinaMasa1->setGeometry(QRect(210, 40, 151, 91));
        QFont font3;
        font3.setPointSize(9);
        font3.setBold(true);
        lbl_TextMaquinaMasa1->setFont(font3);
        lbl_MaquinaMasa1EnProceso = new QLabel(centralwidget);
        lbl_MaquinaMasa1EnProceso->setObjectName(QString::fromUtf8("lbl_MaquinaMasa1EnProceso"));
        lbl_MaquinaMasa1EnProceso->setGeometry(QRect(280, 130, 55, 16));
        lbl_MaquinaMasa1Procesada = new QLabel(centralwidget);
        lbl_MaquinaMasa1Procesada->setObjectName(QString::fromUtf8("lbl_MaquinaMasa1Procesada"));
        lbl_MaquinaMasa1Procesada->setGeometry(QRect(460, 130, 55, 16));
        lbl_TextMaquina1Actual = new QLabel(centralwidget);
        lbl_TextMaquina1Actual->setObjectName(QString::fromUtf8("lbl_TextMaquina1Actual"));
        lbl_TextMaquina1Actual->setGeometry(QRect(220, 120, 51, 21));
        QFont font4;
        font4.setPointSize(8);
        font4.setBold(true);
        lbl_TextMaquina1Actual->setFont(font4);
        lbl_TextMaquina1Procesada = new QLabel(centralwidget);
        lbl_TextMaquina1Procesada->setObjectName(QString::fromUtf8("lbl_TextMaquina1Procesada"));
        lbl_TextMaquina1Procesada->setGeometry(QRect(370, 130, 71, 21));
        lbl_TextMaquina1Procesada->setFont(font);
        btnPausa = new QPushButton(centralwidget);
        btnPausa->setObjectName(QString::fromUtf8("btnPausa"));
        btnPausa->setGeometry(QRect(650, 730, 161, 71));
        btnDetener = new QPushButton(centralwidget);
        btnDetener->setObjectName(QString::fromUtf8("btnDetener"));
        btnDetener->setGeometry(QRect(990, 730, 161, 71));
        lbl_TextMaquinaMasa2 = new QLabel(centralwidget);
        lbl_TextMaquinaMasa2->setObjectName(QString::fromUtf8("lbl_TextMaquinaMasa2"));
        lbl_TextMaquinaMasa2->setGeometry(QRect(210, 160, 151, 91));
        lbl_TextMaquinaMasa2->setFont(font3);
        lbl_TextMaquina2Actual = new QLabel(centralwidget);
        lbl_TextMaquina2Actual->setObjectName(QString::fromUtf8("lbl_TextMaquina2Actual"));
        lbl_TextMaquina2Actual->setGeometry(QRect(220, 250, 55, 16));
        lbl_TextMaquina2Actual->setFont(font);
        lbl_TextMaquina2Procesada = new QLabel(centralwidget);
        lbl_TextMaquina2Procesada->setObjectName(QString::fromUtf8("lbl_TextMaquina2Procesada"));
        lbl_TextMaquina2Procesada->setGeometry(QRect(370, 250, 71, 16));
        lbl_TextMaquina2Procesada->setFont(font);
        lbl_MaquinaMasa2EnProceso = new QLabel(centralwidget);
        lbl_MaquinaMasa2EnProceso->setObjectName(QString::fromUtf8("lbl_MaquinaMasa2EnProceso"));
        lbl_MaquinaMasa2EnProceso->setGeometry(QRect(280, 250, 55, 16));
        lbl_MaquinaMasa2Procesada = new QLabel(centralwidget);
        lbl_MaquinaMasa2Procesada->setObjectName(QString::fromUtf8("lbl_MaquinaMasa2Procesada"));
        lbl_MaquinaMasa2Procesada->setGeometry(QRect(460, 250, 55, 16));
        lbl_TextMaquinaChoco = new QLabel(centralwidget);
        lbl_TextMaquinaChoco->setObjectName(QString::fromUtf8("lbl_TextMaquinaChoco"));
        lbl_TextMaquinaChoco->setGeometry(QRect(210, 280, 151, 91));
        lbl_TextMaquinaChoco->setFont(font3);
        lbl_TextMaquinaChocoActual = new QLabel(centralwidget);
        lbl_TextMaquinaChocoActual->setObjectName(QString::fromUtf8("lbl_TextMaquinaChocoActual"));
        lbl_TextMaquinaChocoActual->setGeometry(QRect(220, 370, 55, 16));
        lbl_TextMaquinaChocoActual->setFont(font);
        lbl_TextMaquinaChocoProcesada = new QLabel(centralwidget);
        lbl_TextMaquinaChocoProcesada->setObjectName(QString::fromUtf8("lbl_TextMaquinaChocoProcesada"));
        lbl_TextMaquinaChocoProcesada->setGeometry(QRect(370, 370, 71, 16));
        lbl_TextMaquinaChocoProcesada->setFont(font);
        lbl_MaquinaChocoProcesada = new QLabel(centralwidget);
        lbl_MaquinaChocoProcesada->setObjectName(QString::fromUtf8("lbl_MaquinaChocoProcesada"));
        lbl_MaquinaChocoProcesada->setGeometry(QRect(460, 370, 55, 16));
        lbl_MaquinaChocoEnProceso = new QLabel(centralwidget);
        lbl_MaquinaChocoEnProceso->setObjectName(QString::fromUtf8("lbl_MaquinaChocoEnProceso"));
        lbl_MaquinaChocoEnProceso->setGeometry(QRect(280, 370, 55, 16));
        lbl_TextBandaTMasaActual = new QLabel(centralwidget);
        lbl_TextBandaTMasaActual->setObjectName(QString::fromUtf8("lbl_TextBandaTMasaActual"));
        lbl_TextBandaTMasaActual->setGeometry(QRect(500, 190, 55, 16));
        lbl_TextBandaTMasaActual->setFont(font);
        lbl_TextBandaChocoProcesada = new QLabel(centralwidget);
        lbl_TextBandaChocoProcesada->setObjectName(QString::fromUtf8("lbl_TextBandaChocoProcesada"));
        lbl_TextBandaChocoProcesada->setGeometry(QRect(640, 360, 31, 16));
        lbl_TextBandaChocoProcesada->setFont(font);
        lbl_BantaTMasaMax = new QLabel(centralwidget);
        lbl_BantaTMasaMax->setObjectName(QString::fromUtf8("lbl_BantaTMasaMax"));
        lbl_BantaTMasaMax->setGeometry(QRect(670, 190, 55, 16));
        lbl_BandaTChocoActual = new QLabel(centralwidget);
        lbl_BandaTChocoActual->setObjectName(QString::fromUtf8("lbl_BandaTChocoActual"));
        lbl_BandaTChocoActual->setGeometry(QRect(554, 360, 51, 20));
        lbl_TextBandaMasa = new QLabel(centralwidget);
        lbl_TextBandaMasa->setObjectName(QString::fromUtf8("lbl_TextBandaMasa"));
        lbl_TextBandaMasa->setGeometry(QRect(500, 140, 351, 51));
        lbl_TextBandaMasa->setFont(font4);
        lbl_BandaTChocoMax = new QLabel(centralwidget);
        lbl_BandaTChocoMax->setObjectName(QString::fromUtf8("lbl_BandaTChocoMax"));
        lbl_BandaTChocoMax->setGeometry(QRect(680, 360, 55, 16));
        lbl_BandaTMasaActual = new QLabel(centralwidget);
        lbl_BandaTMasaActual->setObjectName(QString::fromUtf8("lbl_BandaTMasaActual"));
        lbl_BandaTMasaActual->setGeometry(QRect(550, 190, 16, 16));
        lbl_TextBandaTMasaProcesada = new QLabel(centralwidget);
        lbl_TextBandaTMasaProcesada->setObjectName(QString::fromUtf8("lbl_TextBandaTMasaProcesada"));
        lbl_TextBandaTMasaProcesada->setGeometry(QRect(620, 190, 31, 16));
        lbl_TextBandaTMasaProcesada->setFont(font);
        lbl_TextBandaTChocoActual = new QLabel(centralwidget);
        lbl_TextBandaTChocoActual->setObjectName(QString::fromUtf8("lbl_TextBandaTChocoActual"));
        lbl_TextBandaTChocoActual->setGeometry(QRect(500, 360, 55, 16));
        lbl_TextBandaTChocoActual->setFont(font);
        lbl_TextBandaChoco = new QLabel(centralwidget);
        lbl_TextBandaChoco->setObjectName(QString::fromUtf8("lbl_TextBandaChoco"));
        lbl_TextBandaChoco->setGeometry(QRect(500, 310, 351, 51));
        lbl_TextBandaChoco->setFont(font);
        lbl_MaquinaEnsambladora = new QLabel(centralwidget);
        lbl_MaquinaEnsambladora->setObjectName(QString::fromUtf8("lbl_MaquinaEnsambladora"));
        lbl_MaquinaEnsambladora->setGeometry(QRect(740, 180, 171, 141));
        lbl_MaquinaEnsambladora->setFont(font3);
        lbl_TextEnsambladoraProducida = new QLabel(centralwidget);
        lbl_TextEnsambladoraProducida->setObjectName(QString::fromUtf8("lbl_TextEnsambladoraProducida"));
        lbl_TextEnsambladoraProducida->setGeometry(QRect(750, 330, 81, 16));
        lbl_TextEnsambladoraProducida->setFont(font);
        lbl_EnsambladoraProducida = new QLabel(centralwidget);
        lbl_EnsambladoraProducida->setObjectName(QString::fromUtf8("lbl_EnsambladoraProducida"));
        lbl_EnsambladoraProducida->setGeometry(QRect(830, 330, 55, 16));
        lbl_TextBandaTransportadora = new QLabel(centralwidget);
        lbl_TextBandaTransportadora->setObjectName(QString::fromUtf8("lbl_TextBandaTransportadora"));
        lbl_TextBandaTransportadora->setGeometry(QRect(870, 250, 251, 41));
        lbl_TextBandaTransportadora->setFont(font);
        lbl_TextBandaTEnsambladoraActual = new QLabel(centralwidget);
        lbl_TextBandaTEnsambladoraActual->setObjectName(QString::fromUtf8("lbl_TextBandaTEnsambladoraActual"));
        lbl_TextBandaTEnsambladoraActual->setGeometry(QRect(870, 290, 55, 16));
        lbl_TextBandaTEnsambladoraActual->setFont(font);
        lbl_TextBandaTEnsambladoraMax = new QLabel(centralwidget);
        lbl_TextBandaTEnsambladoraMax->setObjectName(QString::fromUtf8("lbl_TextBandaTEnsambladoraMax"));
        lbl_TextBandaTEnsambladoraMax->setGeometry(QRect(950, 290, 31, 16));
        lbl_TextBandaTEnsambladoraMax->setFont(font);
        lbl_BandaTEnsambladoraActual = new QLabel(centralwidget);
        lbl_BandaTEnsambladoraActual->setObjectName(QString::fromUtf8("lbl_BandaTEnsambladoraActual"));
        lbl_BandaTEnsambladoraActual->setGeometry(QRect(920, 290, 31, 16));
        lbl_BandaTEnsambladoraMax = new QLabel(centralwidget);
        lbl_BandaTEnsambladoraMax->setObjectName(QString::fromUtf8("lbl_BandaTEnsambladoraMax"));
        lbl_BandaTEnsambladoraMax->setGeometry(QRect(990, 290, 55, 16));
        lbl_Horno = new QLabel(centralwidget);
        lbl_Horno->setObjectName(QString::fromUtf8("lbl_Horno"));
        lbl_Horno->setGeometry(QRect(1020, 160, 181, 161));
        lbl_Horno->setFont(font);
        lbl_TextActualHorno = new QLabel(centralwidget);
        lbl_TextActualHorno->setObjectName(QString::fromUtf8("lbl_TextActualHorno"));
        lbl_TextActualHorno->setEnabled(false);
        lbl_TextActualHorno->setGeometry(QRect(990, 320, 51, 16));
        lbl_TextActualHorno->setFont(font);
        lbl_TexthorneadasHorno = new QLabel(centralwidget);
        lbl_TexthorneadasHorno->setObjectName(QString::fromUtf8("lbl_TexthorneadasHorno"));
        lbl_TexthorneadasHorno->setEnabled(false);
        lbl_TexthorneadasHorno->setGeometry(QRect(1060, 320, 81, 16));
        lbl_TexthorneadasHorno->setFont(font4);
        lbl_actualHorno = new QLabel(centralwidget);
        lbl_actualHorno->setObjectName(QString::fromUtf8("lbl_actualHorno"));
        lbl_actualHorno->setEnabled(false);
        lbl_actualHorno->setGeometry(QRect(1040, 320, 21, 16));
        lbl_horneadasHorno = new QLabel(centralwidget);
        lbl_horneadasHorno->setObjectName(QString::fromUtf8("lbl_horneadasHorno"));
        lbl_horneadasHorno->setEnabled(false);
        lbl_horneadasHorno->setGeometry(QRect(1140, 320, 31, 16));
        lbl_Supervisores = new QLabel(centralwidget);
        lbl_Supervisores->setObjectName(QString::fromUtf8("lbl_Supervisores"));
        lbl_Supervisores->setGeometry(QRect(1160, 210, 101, 171));
        lbl_Supervisores->setFont(font);
        lbl_TextActualSupervisores = new QLabel(centralwidget);
        lbl_TextActualSupervisores->setObjectName(QString::fromUtf8("lbl_TextActualSupervisores"));
        lbl_TextActualSupervisores->setGeometry(QRect(1180, 380, 60, 16));
        lbl_TextActualSupervisores->setFont(font);
        lbl_actualSupervisores = new QLabel(centralwidget);
        lbl_actualSupervisores->setObjectName(QString::fromUtf8("lbl_actualSupervisores"));
        lbl_actualSupervisores->setGeometry(QRect(1240, 380, 60, 16));
        grupoEstadoMaquina1 = new QGroupBox(centralwidget);
        grupoEstadoMaquina1->setObjectName(QString::fromUtf8("grupoEstadoMaquina1"));
        grupoEstadoMaquina1->setGeometry(QRect(370, 40, 111, 91));
        radioButtonEncenderMaquina1 = new QRadioButton(grupoEstadoMaquina1);
        radioButtonEncenderMaquina1->setObjectName(QString::fromUtf8("radioButtonEncenderMaquina1"));
        radioButtonEncenderMaquina1->setGeometry(QRect(10, 22, 51, 20));
        radioButtonApagarMaquina1 = new QRadioButton(grupoEstadoMaquina1);
        radioButtonApagarMaquina1->setObjectName(QString::fromUtf8("radioButtonApagarMaquina1"));
        radioButtonApagarMaquina1->setGeometry(QRect(10, 40, 51, 21));
        btnCambiarEstadoMaquina1 = new QPushButton(grupoEstadoMaquina1);
        btnCambiarEstadoMaquina1->setObjectName(QString::fromUtf8("btnCambiarEstadoMaquina1"));
        btnCambiarEstadoMaquina1->setGeometry(QRect(20, 60, 80, 25));
        grupoEstadoMaquina2 = new QGroupBox(centralwidget);
        grupoEstadoMaquina2->setObjectName(QString::fromUtf8("grupoEstadoMaquina2"));
        grupoEstadoMaquina2->setGeometry(QRect(370, 160, 111, 91));
        radioButtonEncenderMaquina2 = new QRadioButton(grupoEstadoMaquina2);
        radioButtonEncenderMaquina2->setObjectName(QString::fromUtf8("radioButtonEncenderMaquina2"));
        radioButtonEncenderMaquina2->setGeometry(QRect(10, 22, 51, 20));
        radioButtonApagarMaquina2 = new QRadioButton(grupoEstadoMaquina2);
        radioButtonApagarMaquina2->setObjectName(QString::fromUtf8("radioButtonApagarMaquina2"));
        radioButtonApagarMaquina2->setGeometry(QRect(10, 40, 51, 21));
        btnCambiarEstadoMaquina2 = new QPushButton(grupoEstadoMaquina2);
        btnCambiarEstadoMaquina2->setObjectName(QString::fromUtf8("btnCambiarEstadoMaquina2"));
        btnCambiarEstadoMaquina2->setGeometry(QRect(20, 60, 80, 25));
        grupoEstadoMaquina3 = new QGroupBox(centralwidget);
        grupoEstadoMaquina3->setObjectName(QString::fromUtf8("grupoEstadoMaquina3"));
        grupoEstadoMaquina3->setGeometry(QRect(370, 280, 111, 91));
        radioButtonEncenderMaquina3 = new QRadioButton(grupoEstadoMaquina3);
        radioButtonEncenderMaquina3->setObjectName(QString::fromUtf8("radioButtonEncenderMaquina3"));
        radioButtonEncenderMaquina3->setGeometry(QRect(10, 22, 51, 20));
        radioButtonApagarMaquina3 = new QRadioButton(grupoEstadoMaquina3);
        radioButtonApagarMaquina3->setObjectName(QString::fromUtf8("radioButtonApagarMaquina3"));
        radioButtonApagarMaquina3->setGeometry(QRect(10, 40, 51, 21));
        btnCambiarEstadoMaquina3 = new QPushButton(grupoEstadoMaquina3);
        btnCambiarEstadoMaquina3->setObjectName(QString::fromUtf8("btnCambiarEstadoMaquina3"));
        btnCambiarEstadoMaquina3->setGeometry(QRect(20, 60, 80, 25));
        btnReanudar = new QPushButton(centralwidget);
        btnReanudar->setObjectName(QString::fromUtf8("btnReanudar"));
        btnReanudar->setGeometry(QRect(820, 730, 161, 71));
        lbl_TextSupervisoresAceptadas = new QLabel(centralwidget);
        lbl_TextSupervisoresAceptadas->setObjectName(QString::fromUtf8("lbl_TextSupervisoresAceptadas"));
        lbl_TextSupervisoresAceptadas->setGeometry(QRect(1170, 130, 121, 16));
        lbl_TextSupervisoresAceptadas->setFont(font);
        lbl_TextSupervisoresRechazadas = new QLabel(centralwidget);
        lbl_TextSupervisoresRechazadas->setObjectName(QString::fromUtf8("lbl_TextSupervisoresRechazadas"));
        lbl_TextSupervisoresRechazadas->setGeometry(QRect(1170, 150, 131, 16));
        lbl_TextSupervisoresRechazadas->setFont(font);
        lbl_SupervisoresAceptadas = new QLabel(centralwidget);
        lbl_SupervisoresAceptadas->setObjectName(QString::fromUtf8("lbl_SupervisoresAceptadas"));
        lbl_SupervisoresAceptadas->setGeometry(QRect(1300, 130, 55, 16));
        lbl_SupervisoresRechazadas = new QLabel(centralwidget);
        lbl_SupervisoresRechazadas->setObjectName(QString::fromUtf8("lbl_SupervisoresRechazadas"));
        lbl_SupervisoresRechazadas->setGeometry(QRect(1300, 150, 55, 16));
        lbl_Carrito = new QLabel(centralwidget);
        lbl_Carrito->setObjectName(QString::fromUtf8("lbl_Carrito"));
        lbl_Carrito->setGeometry(QRect(100, 110, 91, 81));
        lblSup1 = new QLabel(centralwidget);
        lblSup1->setObjectName(QString::fromUtf8("lblSup1"));
        lblSup1->setGeometry(QRect(1270, 220, 60, 71));
        lblSup2 = new QLabel(centralwidget);
        lblSup2->setObjectName(QString::fromUtf8("lblSup2"));
        lblSup2->setGeometry(QRect(1270, 310, 60, 71));
        lbl_TextAceptadasSup2 = new QLabel(centralwidget);
        lbl_TextAceptadasSup2->setObjectName(QString::fromUtf8("lbl_TextAceptadasSup2"));
        lbl_TextAceptadasSup2->setGeometry(QRect(1170, 170, 121, 16));
        lbl_TextAceptadasSup2->setFont(font);
        lbl_TextRechazadasSup2 = new QLabel(centralwidget);
        lbl_TextRechazadasSup2->setObjectName(QString::fromUtf8("lbl_TextRechazadasSup2"));
        lbl_TextRechazadasSup2->setGeometry(QRect(1170, 190, 121, 16));
        lbl_TextRechazadasSup2->setFont(font);
        lbl_AceptadasSup2 = new QLabel(centralwidget);
        lbl_AceptadasSup2->setObjectName(QString::fromUtf8("lbl_AceptadasSup2"));
        lbl_AceptadasSup2->setGeometry(QRect(1300, 170, 55, 16));
        lbl_RechazadasSup2 = new QLabel(centralwidget);
        lbl_RechazadasSup2->setObjectName(QString::fromUtf8("lbl_RechazadasSup2"));
        lbl_RechazadasSup2->setGeometry(QRect(1300, 190, 55, 16));
        lbl_imgEmpacadora = new QLabel(centralwidget);
        lbl_imgEmpacadora->setObjectName(QString::fromUtf8("lbl_imgEmpacadora"));
        lbl_imgEmpacadora->setGeometry(QRect(1350, 200, 231, 191));
        lbl_imgAlmacen1 = new QLabel(centralwidget);
        lbl_imgAlmacen1->setObjectName(QString::fromUtf8("lbl_imgAlmacen1"));
        lbl_imgAlmacen1->setGeometry(QRect(10, 220, 181, 181));
        lbl_imgAlmacenFinal = new QLabel(centralwidget);
        lbl_imgAlmacenFinal->setObjectName(QString::fromUtf8("lbl_imgAlmacenFinal"));
        lbl_imgAlmacenFinal->setGeometry(QRect(1120, 480, 211, 181));
        grupoHorno = new QGroupBox(centralwidget);
        grupoHorno->setObjectName(QString::fromUtf8("grupoHorno"));
        grupoHorno->setGeometry(QRect(990, 10, 111, 91));
        btnCambiarEstadoHorno = new QPushButton(grupoHorno);
        btnCambiarEstadoHorno->setObjectName(QString::fromUtf8("btnCambiarEstadoHorno"));
        btnCambiarEstadoHorno->setGeometry(QRect(30, 60, 61, 21));
        radioButtonEncenderHorno = new QRadioButton(grupoHorno);
        radioButtonEncenderHorno->setObjectName(QString::fromUtf8("radioButtonEncenderHorno"));
        radioButtonEncenderHorno->setGeometry(QRect(10, 20, 97, 22));
        radioButtonApagarHorno = new QRadioButton(grupoHorno);
        radioButtonApagarHorno->setObjectName(QString::fromUtf8("radioButtonApagarHorno"));
        radioButtonApagarHorno->setGeometry(QRect(10, 40, 97, 22));
        groupBox = new QGroupBox(centralwidget);
        groupBox->setObjectName(QString::fromUtf8("groupBox"));
        groupBox->setGeometry(QRect(740, 20, 121, 91));
        radioButtonEncenderEnsambladora = new QRadioButton(groupBox);
        radioButtonEncenderEnsambladora->setObjectName(QString::fromUtf8("radioButtonEncenderEnsambladora"));
        radioButtonEncenderEnsambladora->setGeometry(QRect(10, 20, 97, 22));
        radioButtonApagarEnsambladora = new QRadioButton(groupBox);
        radioButtonApagarEnsambladora->setObjectName(QString::fromUtf8("radioButtonApagarEnsambladora"));
        radioButtonApagarEnsambladora->setGeometry(QRect(10, 40, 97, 22));
        btnCambiarEstadoEnsambladora = new QPushButton(groupBox);
        btnCambiarEstadoEnsambladora->setObjectName(QString::fromUtf8("btnCambiarEstadoEnsambladora"));
        btnCambiarEstadoEnsambladora->setGeometry(QRect(30, 60, 71, 21));
        lbl_TextMaxSupervisores = new QLabel(centralwidget);
        lbl_TextMaxSupervisores->setObjectName(QString::fromUtf8("lbl_TextMaxSupervisores"));
        lbl_TextMaxSupervisores->setGeometry(QRect(1180, 400, 55, 16));
        lbl_TextMaxSupervisores->setFont(font);
        lbl_SupervisoresMax = new QLabel(centralwidget);
        lbl_SupervisoresMax->setObjectName(QString::fromUtf8("lbl_SupervisoresMax"));
        lbl_SupervisoresMax->setGeometry(QRect(1240, 400, 55, 16));
        tableWidget = new QTableWidget(centralwidget);
        if (tableWidget->columnCount() < 3)
            tableWidget->setColumnCount(3);
        QFont font5;
        font5.setPointSize(7);
        QTableWidgetItem *__qtablewidgetitem = new QTableWidgetItem();
        __qtablewidgetitem->setFont(font5);
        tableWidget->setHorizontalHeaderItem(0, __qtablewidgetitem);
        QTableWidgetItem *__qtablewidgetitem1 = new QTableWidgetItem();
        __qtablewidgetitem1->setFont(font5);
        tableWidget->setHorizontalHeaderItem(1, __qtablewidgetitem1);
        QTableWidgetItem *__qtablewidgetitem2 = new QTableWidgetItem();
        __qtablewidgetitem2->setFont(font5);
        tableWidget->setHorizontalHeaderItem(2, __qtablewidgetitem2);
        tableWidget->setObjectName(QString::fromUtf8("tableWidget"));
        tableWidget->setGeometry(QRect(370, 480, 351, 231));
        tableWidget->setFont(font5);
        label = new QLabel(centralwidget);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(370, 460, 161, 16));
        label->setFont(font);
        tablaBandejas = new QTableWidget(centralwidget);
        if (tablaBandejas->columnCount() < 2)
            tablaBandejas->setColumnCount(2);
        QTableWidgetItem *__qtablewidgetitem3 = new QTableWidgetItem();
        tablaBandejas->setHorizontalHeaderItem(0, __qtablewidgetitem3);
        QTableWidgetItem *__qtablewidgetitem4 = new QTableWidgetItem();
        tablaBandejas->setHorizontalHeaderItem(1, __qtablewidgetitem4);
        if (tablaBandejas->rowCount() < 6)
            tablaBandejas->setRowCount(6);
        QTableWidgetItem *__qtablewidgetitem5 = new QTableWidgetItem();
        tablaBandejas->setVerticalHeaderItem(0, __qtablewidgetitem5);
        QTableWidgetItem *__qtablewidgetitem6 = new QTableWidgetItem();
        tablaBandejas->setVerticalHeaderItem(1, __qtablewidgetitem6);
        QTableWidgetItem *__qtablewidgetitem7 = new QTableWidgetItem();
        tablaBandejas->setVerticalHeaderItem(2, __qtablewidgetitem7);
        QTableWidgetItem *__qtablewidgetitem8 = new QTableWidgetItem();
        tablaBandejas->setVerticalHeaderItem(3, __qtablewidgetitem8);
        QTableWidgetItem *__qtablewidgetitem9 = new QTableWidgetItem();
        tablaBandejas->setVerticalHeaderItem(4, __qtablewidgetitem9);
        QTableWidgetItem *__qtablewidgetitem10 = new QTableWidgetItem();
        tablaBandejas->setVerticalHeaderItem(5, __qtablewidgetitem10);
        tablaBandejas->setObjectName(QString::fromUtf8("tablaBandejas"));
        tablaBandejas->setGeometry(QRect(730, 460, 261, 251));
        label_2 = new QLabel(centralwidget);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(740, 430, 211, 16));
        label_2->setFont(font);
        tablaTransportes = new QTableWidget(centralwidget);
        if (tablaTransportes->columnCount() < 3)
            tablaTransportes->setColumnCount(3);
        QTableWidgetItem *__qtablewidgetitem11 = new QTableWidgetItem();
        __qtablewidgetitem11->setFont(font5);
        tablaTransportes->setHorizontalHeaderItem(0, __qtablewidgetitem11);
        QTableWidgetItem *__qtablewidgetitem12 = new QTableWidgetItem();
        __qtablewidgetitem12->setFont(font5);
        tablaTransportes->setHorizontalHeaderItem(1, __qtablewidgetitem12);
        QTableWidgetItem *__qtablewidgetitem13 = new QTableWidgetItem();
        __qtablewidgetitem13->setFont(font5);
        tablaTransportes->setHorizontalHeaderItem(2, __qtablewidgetitem13);
        tablaTransportes->setObjectName(QString::fromUtf8("tablaTransportes"));
        tablaTransportes->setGeometry(QRect(1090, 640, 351, 101));
        tablaTransportes->setFont(font5);
        VentanaPrincipal->setCentralWidget(centralwidget);
        menubar = new QMenuBar(VentanaPrincipal);
        menubar->setObjectName(QString::fromUtf8("menubar"));
        menubar->setGeometry(QRect(0, 0, 1597, 25));
        VentanaPrincipal->setMenuBar(menubar);
        statusbar = new QStatusBar(VentanaPrincipal);
        statusbar->setObjectName(QString::fromUtf8("statusbar"));
        VentanaPrincipal->setStatusBar(statusbar);

        retranslateUi(VentanaPrincipal);

        QMetaObject::connectSlotsByName(VentanaPrincipal);
    } // setupUi

    void retranslateUi(QMainWindow *VentanaPrincipal)
    {
        VentanaPrincipal->setWindowTitle(QCoreApplication::translate("VentanaPrincipal", "F\303\241brica de Galletas", nullptr));
        lblCantidadGalletas->setText(QCoreApplication::translate("VentanaPrincipal", "0", nullptr));
#if QT_CONFIG(tooltip)
        btnIniciar->setToolTip(QCoreApplication::translate("VentanaPrincipal", "<html><head/><body><p><br/></p></body></html>", nullptr));
#endif // QT_CONFIG(tooltip)
        btnIniciar->setText(QCoreApplication::translate("VentanaPrincipal", "Iniciar", nullptr));
        lblChoco->setText(QCoreApplication::translate("VentanaPrincipal", "0", nullptr));
        lblMasa->setText(QCoreApplication::translate("VentanaPrincipal", "0", nullptr));
        lbl_TextGalletasPlani->setText(QCoreApplication::translate("VentanaPrincipal", "Cantidad de galletas: ", nullptr));
        lbl_TextMasaPlani->setText(QCoreApplication::translate("VentanaPrincipal", "Cantidad masa: ", nullptr));
        lbl_TextChocoPlani->setText(QCoreApplication::translate("VentanaPrincipal", "Cantidad chocolate: ", nullptr));
        lbl_TextPlani->setText(QCoreApplication::translate("VentanaPrincipal", "Planificador", nullptr));
        lbl_TextMaquinaMasa1->setText(QCoreApplication::translate("VentanaPrincipal", "Maquina Masa 1", nullptr));
        lbl_MaquinaMasa1EnProceso->setText(QCoreApplication::translate("VentanaPrincipal", "0", nullptr));
        lbl_MaquinaMasa1Procesada->setText(QCoreApplication::translate("VentanaPrincipal", "0", nullptr));
        lbl_TextMaquina1Actual->setText(QCoreApplication::translate("VentanaPrincipal", "Actual: ", nullptr));
        lbl_TextMaquina1Procesada->setText(QCoreApplication::translate("VentanaPrincipal", "Procesada: ", nullptr));
        btnPausa->setText(QCoreApplication::translate("VentanaPrincipal", "Pausa", nullptr));
        btnDetener->setText(QCoreApplication::translate("VentanaPrincipal", "Detener", nullptr));
        lbl_TextMaquinaMasa2->setText(QCoreApplication::translate("VentanaPrincipal", "Maquina Masa 2", nullptr));
        lbl_TextMaquina2Actual->setText(QCoreApplication::translate("VentanaPrincipal", "Actual:", nullptr));
        lbl_TextMaquina2Procesada->setText(QCoreApplication::translate("VentanaPrincipal", "Procesada: ", nullptr));
        lbl_MaquinaMasa2EnProceso->setText(QCoreApplication::translate("VentanaPrincipal", "0", nullptr));
        lbl_MaquinaMasa2Procesada->setText(QCoreApplication::translate("VentanaPrincipal", "0", nullptr));
        lbl_TextMaquinaChoco->setText(QCoreApplication::translate("VentanaPrincipal", "Maquina Chocolate", nullptr));
        lbl_TextMaquinaChocoActual->setText(QCoreApplication::translate("VentanaPrincipal", "Actual:", nullptr));
        lbl_TextMaquinaChocoProcesada->setText(QCoreApplication::translate("VentanaPrincipal", "Procesada:", nullptr));
        lbl_MaquinaChocoProcesada->setText(QCoreApplication::translate("VentanaPrincipal", "0", nullptr));
        lbl_MaquinaChocoEnProceso->setText(QCoreApplication::translate("VentanaPrincipal", "0", nullptr));
        lbl_TextBandaTMasaActual->setText(QCoreApplication::translate("VentanaPrincipal", "Actual:", nullptr));
        lbl_TextBandaChocoProcesada->setText(QCoreApplication::translate("VentanaPrincipal", "Max:", nullptr));
        lbl_BantaTMasaMax->setText(QCoreApplication::translate("VentanaPrincipal", "0", nullptr));
        lbl_BandaTChocoActual->setText(QCoreApplication::translate("VentanaPrincipal", "0", nullptr));
        lbl_TextBandaMasa->setText(QCoreApplication::translate("VentanaPrincipal", "Banda Transportadora Masa", nullptr));
        lbl_BandaTChocoMax->setText(QCoreApplication::translate("VentanaPrincipal", "0", nullptr));
        lbl_BandaTMasaActual->setText(QCoreApplication::translate("VentanaPrincipal", "0", nullptr));
        lbl_TextBandaTMasaProcesada->setText(QCoreApplication::translate("VentanaPrincipal", "Max:", nullptr));
        lbl_TextBandaTChocoActual->setText(QCoreApplication::translate("VentanaPrincipal", "Actual:", nullptr));
        lbl_TextBandaChoco->setText(QCoreApplication::translate("VentanaPrincipal", "Banda Transportadora Chocolate", nullptr));
        lbl_MaquinaEnsambladora->setText(QCoreApplication::translate("VentanaPrincipal", "Maquina Ensambladora", nullptr));
        lbl_TextEnsambladoraProducida->setText(QCoreApplication::translate("VentanaPrincipal", "Producidas:", nullptr));
        lbl_EnsambladoraProducida->setText(QCoreApplication::translate("VentanaPrincipal", "0", nullptr));
        lbl_TextBandaTransportadora->setText(QCoreApplication::translate("VentanaPrincipal", "Banda Transportadora", nullptr));
        lbl_TextBandaTEnsambladoraActual->setText(QCoreApplication::translate("VentanaPrincipal", "Actual:", nullptr));
        lbl_TextBandaTEnsambladoraMax->setText(QCoreApplication::translate("VentanaPrincipal", "Max:", nullptr));
        lbl_BandaTEnsambladoraActual->setText(QCoreApplication::translate("VentanaPrincipal", "0", nullptr));
        lbl_BandaTEnsambladoraMax->setText(QCoreApplication::translate("VentanaPrincipal", "0", nullptr));
        lbl_Horno->setText(QCoreApplication::translate("VentanaPrincipal", "Horno", nullptr));
        lbl_TextActualHorno->setText(QCoreApplication::translate("VentanaPrincipal", "Actual:", nullptr));
        lbl_TexthorneadasHorno->setText(QCoreApplication::translate("VentanaPrincipal", "Horneadas:", nullptr));
        lbl_actualHorno->setText(QCoreApplication::translate("VentanaPrincipal", "0", nullptr));
        lbl_horneadasHorno->setText(QCoreApplication::translate("VentanaPrincipal", "0", nullptr));
        lbl_Supervisores->setText(QCoreApplication::translate("VentanaPrincipal", "Supervisores", nullptr));
        lbl_TextActualSupervisores->setText(QCoreApplication::translate("VentanaPrincipal", "Actual:", nullptr));
        lbl_actualSupervisores->setText(QCoreApplication::translate("VentanaPrincipal", "0", nullptr));
        grupoEstadoMaquina1->setTitle(QCoreApplication::translate("VentanaPrincipal", "Estado", nullptr));
        radioButtonEncenderMaquina1->setText(QCoreApplication::translate("VentanaPrincipal", "ON", nullptr));
        radioButtonApagarMaquina1->setText(QCoreApplication::translate("VentanaPrincipal", "OFF", nullptr));
        btnCambiarEstadoMaquina1->setText(QCoreApplication::translate("VentanaPrincipal", "Aceptar", nullptr));
        grupoEstadoMaquina2->setTitle(QCoreApplication::translate("VentanaPrincipal", "Estado", nullptr));
        radioButtonEncenderMaquina2->setText(QCoreApplication::translate("VentanaPrincipal", "ON", nullptr));
        radioButtonApagarMaquina2->setText(QCoreApplication::translate("VentanaPrincipal", "OFF", nullptr));
        btnCambiarEstadoMaquina2->setText(QCoreApplication::translate("VentanaPrincipal", "Aceptar", nullptr));
        grupoEstadoMaquina3->setTitle(QCoreApplication::translate("VentanaPrincipal", "Estado", nullptr));
        radioButtonEncenderMaquina3->setText(QCoreApplication::translate("VentanaPrincipal", "ON", nullptr));
        radioButtonApagarMaquina3->setText(QCoreApplication::translate("VentanaPrincipal", "OFF", nullptr));
        btnCambiarEstadoMaquina3->setText(QCoreApplication::translate("VentanaPrincipal", "Aceptar", nullptr));
        btnReanudar->setText(QCoreApplication::translate("VentanaPrincipal", "Reanudar", nullptr));
        lbl_TextSupervisoresAceptadas->setText(QCoreApplication::translate("VentanaPrincipal", "Aceptadas Sup 1:", nullptr));
        lbl_TextSupervisoresRechazadas->setText(QCoreApplication::translate("VentanaPrincipal", "Rechazadas Sup 1:", nullptr));
        lbl_SupervisoresAceptadas->setText(QCoreApplication::translate("VentanaPrincipal", "0", nullptr));
        lbl_SupervisoresRechazadas->setText(QCoreApplication::translate("VentanaPrincipal", "0", nullptr));
        lbl_Carrito->setText(QCoreApplication::translate("VentanaPrincipal", "TextLabel", nullptr));
        lblSup1->setText(QCoreApplication::translate("VentanaPrincipal", "TextLabel", nullptr));
        lblSup2->setText(QCoreApplication::translate("VentanaPrincipal", "TextLabel", nullptr));
        lbl_TextAceptadasSup2->setText(QCoreApplication::translate("VentanaPrincipal", "Aceptadas Sup 2:", nullptr));
        lbl_TextRechazadasSup2->setText(QCoreApplication::translate("VentanaPrincipal", "Rechazadas Sup 2:", nullptr));
        lbl_AceptadasSup2->setText(QCoreApplication::translate("VentanaPrincipal", "0", nullptr));
        lbl_RechazadasSup2->setText(QCoreApplication::translate("VentanaPrincipal", "0", nullptr));
        lbl_imgEmpacadora->setText(QCoreApplication::translate("VentanaPrincipal", "TextLabel", nullptr));
        lbl_imgAlmacen1->setText(QCoreApplication::translate("VentanaPrincipal", "TextLabel", nullptr));
        lbl_imgAlmacenFinal->setText(QCoreApplication::translate("VentanaPrincipal", "TextLabel", nullptr));
        grupoHorno->setTitle(QCoreApplication::translate("VentanaPrincipal", "Estado", nullptr));
        btnCambiarEstadoHorno->setText(QCoreApplication::translate("VentanaPrincipal", "Aceptar", nullptr));
        radioButtonEncenderHorno->setText(QCoreApplication::translate("VentanaPrincipal", "ON", nullptr));
        radioButtonApagarHorno->setText(QCoreApplication::translate("VentanaPrincipal", "OFF", nullptr));
        groupBox->setTitle(QCoreApplication::translate("VentanaPrincipal", "Estado", nullptr));
        radioButtonEncenderEnsambladora->setText(QCoreApplication::translate("VentanaPrincipal", "ON", nullptr));
        radioButtonApagarEnsambladora->setText(QCoreApplication::translate("VentanaPrincipal", "OFF", nullptr));
        btnCambiarEstadoEnsambladora->setText(QCoreApplication::translate("VentanaPrincipal", "Aceptar", nullptr));
        lbl_TextMaxSupervisores->setText(QCoreApplication::translate("VentanaPrincipal", "Max:", nullptr));
        lbl_SupervisoresMax->setText(QCoreApplication::translate("VentanaPrincipal", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem = tableWidget->horizontalHeaderItem(0);
        ___qtablewidgetitem->setText(QCoreApplication::translate("VentanaPrincipal", "Cantidad", nullptr));
        QTableWidgetItem *___qtablewidgetitem1 = tableWidget->horizontalHeaderItem(1);
        ___qtablewidgetitem1->setText(QCoreApplication::translate("VentanaPrincipal", "ID", nullptr));
        QTableWidgetItem *___qtablewidgetitem2 = tableWidget->horizontalHeaderItem(2);
        ___qtablewidgetitem2->setText(QCoreApplication::translate("VentanaPrincipal", "Estado", nullptr));
        label->setText(QCoreApplication::translate("VentanaPrincipal", "Cola Peticiones Almacen", nullptr));
        QTableWidgetItem *___qtablewidgetitem3 = tablaBandejas->horizontalHeaderItem(0);
        ___qtablewidgetitem3->setText(QCoreApplication::translate("VentanaPrincipal", "Actual", nullptr));
        QTableWidgetItem *___qtablewidgetitem4 = tablaBandejas->horizontalHeaderItem(1);
        ___qtablewidgetitem4->setText(QCoreApplication::translate("VentanaPrincipal", "Procesadas", nullptr));
        QTableWidgetItem *___qtablewidgetitem5 = tablaBandejas->verticalHeaderItem(0);
        ___qtablewidgetitem5->setText(QCoreApplication::translate("VentanaPrincipal", "1", nullptr));
        QTableWidgetItem *___qtablewidgetitem6 = tablaBandejas->verticalHeaderItem(1);
        ___qtablewidgetitem6->setText(QCoreApplication::translate("VentanaPrincipal", "2", nullptr));
        QTableWidgetItem *___qtablewidgetitem7 = tablaBandejas->verticalHeaderItem(2);
        ___qtablewidgetitem7->setText(QCoreApplication::translate("VentanaPrincipal", "3", nullptr));
        QTableWidgetItem *___qtablewidgetitem8 = tablaBandejas->verticalHeaderItem(3);
        ___qtablewidgetitem8->setText(QCoreApplication::translate("VentanaPrincipal", "4", nullptr));
        QTableWidgetItem *___qtablewidgetitem9 = tablaBandejas->verticalHeaderItem(4);
        ___qtablewidgetitem9->setText(QCoreApplication::translate("VentanaPrincipal", "5", nullptr));
        QTableWidgetItem *___qtablewidgetitem10 = tablaBandejas->verticalHeaderItem(5);
        ___qtablewidgetitem10->setText(QCoreApplication::translate("VentanaPrincipal", "6", nullptr));
        label_2->setText(QCoreApplication::translate("VentanaPrincipal", "Bandejas Horno", nullptr));
        QTableWidgetItem *___qtablewidgetitem11 = tablaTransportes->horizontalHeaderItem(0);
        ___qtablewidgetitem11->setText(QCoreApplication::translate("VentanaPrincipal", "Tipo", nullptr));
        QTableWidgetItem *___qtablewidgetitem12 = tablaTransportes->horizontalHeaderItem(1);
        ___qtablewidgetitem12->setText(QCoreApplication::translate("VentanaPrincipal", "Actual", nullptr));
        QTableWidgetItem *___qtablewidgetitem13 = tablaTransportes->horizontalHeaderItem(2);
        ___qtablewidgetitem13->setText(QCoreApplication::translate("VentanaPrincipal", "Max", nullptr));
    } // retranslateUi

};

namespace Ui {
    class VentanaPrincipal: public Ui_VentanaPrincipal {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_VENTANAPRINCIPAL_H
